export const defaultLanguage = "en";
export const supportedLanguages = ["en", "sr", "de", "uk", "he"];
export const languageDirectionMap = {
  en: "ltr",
  sr: "ltr",
  de: "ltr",
  uk: "ltr",
  he: "rtl",
};

export const calendlyUrl = "https://calendly.com/prokopov94/30min";
export const contactEmail = "hello@shelf8.com";

export const languageOptions = [
  { code: "en", flag: "🇬🇧", label: "English" },
  { code: "sr", flag: "🇷🇸", label: "Srpski" },
  { code: "de", flag: "🇩🇪", label: "Deutsch" },
  { code: "uk", flag: "🇺🇦", label: "Українська" },
  { code: "he", flag: "🇮🇱", label: "עברית" },
];

const en = {
  meta: {
    landingTitle: "Shelf8 | Retail intelligence for grocery operators",
    landingDescription:
      "Shelf8 helps stores sell more, waste less, keep shelves full, and make daily decisions with less guesswork.",
    privacyTitle: "Privacy Policy | Shelf8",
    privacyDescription: "How Shelf8 collects, uses, and protects website and booking information.",
    termsTitle: "Terms of Use | Shelf8",
    termsDescription: "The terms that govern use of the Shelf8 website and booked demo calls.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Book a Demo",
    seeHowItWorks: "See How It Works",
    allRightsReserved: "All rights reserved.",
    menu: "Menu",
    close: "Close",
    freeBadge: "Free for the first 3 months",
    monthAfter: "/ month after",
    backHome: "Back to home",
    updated: "Last updated",
  },
  nav: {
    howItWorks: "How It Works",
    benefits: "Key Benefits",
    examples: "Examples",
    pricing: "Pricing",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
  },
  hero: {
    eyebrow: "For grocery stores and retail teams",
    titleStart: "Waste less food.",
    titleMiddle: "Keep shelves full.",
    titleAccent: "Grow sales.",
    subtitle:
      "See what sells well, what slows down, what needs reordering, and what may turn into waste.",
    metrics: [
      { label: "Revenue MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Gross Margin", value: "34.6%" },
      { label: "Inv. Turnover", value: "3.2×", note: "Healthy" },
    ],
    chartTitle: "Revenue by Category · 30 days",
    categories: [
      { label: "Beverages", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Dairy", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Seafood", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "Meat", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Stockout Predictions",
    stockouts: [
      { name: "Free-Range Eggs 12pk", meta: "Dairy · 40 units", status: "1.9d · Critical", tone: "danger" },
      { name: "Cheddar Cheese 200g", meta: "Dairy · 55 units", status: "6.4d · Warning", tone: "warning" },
      { name: "Whole Milk 1L", meta: "Dairy · 35 units", status: "17.5d · OK", tone: "success" },
      { name: "Sourdough Bread", meta: "Bakery · 143 units", status: "7.9d · OK", tone: "success" },
      { name: "Greek Yogurt 500g", meta: "Dairy · 93 units", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "How It Works",
    titleStart: "Upload your data.",
    titleAccent: "See what needs fixing",
    lead: "Send your reports or files. We show what to reorder, what to watch, and where you lose money.",
    steps: [
      {
        icon: "🔗",
        title: "Upload",
        body: "Upload receipts or reports.",
      },
      {
        icon: "⚙️",
        title: "Organize",
        body: "We organize everything.",
      },
      {
        icon: "🧠",
        title: "See Problems",
        body: "See problems in your stock.",
      },
      {
        icon: "📊",
        title: "Take Action",
        body: "Know what to fix next.",
      },
    ],
  },
  benefits: {
    eyebrow: "Key Benefits",
    titleStart: "What you can see",
    titleAccent: "inside Shelf8",
    inventory: {
      tag: "Inventory",
      titleStart: "Keep your shelves",
      titleAccent: "full",
      body: "See what is running out and reorder before customers notice.",
      list: [
        "Catch low stock early",
        "Avoid empty shelves",
        "Track stock value",
        "Know what sells fast",
      ],
      screenLabel: "Inventory",
      topCards: [
        { label: "Stock on Hand", value: "7.0K" },
        { label: "Inv. Value", value: "€31.2K" },
        { label: "Active SKUs", value: "1.5K" },
      ],
      panelTitle: "Products That Need Attention",
      rows: [
        { label: "Free-Range Eggs 12pk", status: "1.9d · Critical", tone: "danger" },
        { label: "Cheddar Cheese 200g", status: "6.4d · Warning", tone: "warning" },
        { label: "Whole Milk 1L", status: "17.5d · OK", tone: "success" },
        { label: "Organic Bananas", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Sales",
      titleStart: "Know what actually",
      titleAccent: "sells",
      body: "See which products bring money and which just take up space.",
      list: [
        "See top products",
        "Spot slow movers",
        "Track revenue and margin",
      ],
      screenLabel: "Sales",
      topCards: [
        { label: "Total Revenue", value: "€25.6K" },
        { label: "Gross Profit", value: "€14.4K", tone: "success" },
        { label: "Gross Margin", value: "56.3%" },
      ],
      panelTitle: "Best Sellers",
      rows: [
        { label: "Avocado", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Espresso Beans", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Pasta", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Salmon", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Alerts",
      titleStart: "Fix problems before",
      titleAccent: "they cost you",
      body: "See where you lose money and what to do about it.",
      list: [],
      screenLabel: "Alerts",
      notices: [
        {
          icon: "📉",
          title: "Lost Sales",
          body: "Products are out of stock — you are missing revenue.",
          tone: "danger-soft",
        },
        {
          icon: "⚠️",
          title: "Expiry Risk",
          body: "Some items will not sell before they expire.",
          tone: "warning-soft",
        },
        {
          icon: "💡",
          title: "Pricing Tip",
          body: "Small price changes can increase revenue.",
          tone: "success-soft",
        },
      ],
    },
  },
  examples: {
    eyebrow: "Examples",
    titleStart: "See what needs",
    titleAccent: "action today",
    lead: "",
    cards: [
      {
        title: "Milk may run out in 2 days",
        body: "Reorder before the shelf goes empty.",
        icon: "🥛",
        badge: "LOW",
      },
      {
        title: "Yogurt is not selling",
        body: "Order less or promote it.",
        icon: "🥣",
        badge: "SLOW",
      },
      {
        title: "Eggs sell fast, cheese runs out",
        body: "Fix the stock gap.",
        icon: "🥚",
        badge: "GAP",
      },
      {
        title: "Bakery waste is growing this week",
        body: "Act before more is lost.",
        icon: "🥐",
        badge: "WASTE",
      },
    ],
  },
  trust: {
    eyebrow: "Setup",
    titleStart: "Use the data",
    titleAccent: "you already have",
    lead: "No setup. Send your files and get a clear view of your store.",
    sourcesTitle: "What you can send",
    sources: [
      {
        icon: "🧾",
        title: "Receipts",
        body: "Till receipts or receipt exports",
      },
      {
        icon: "📊",
        title: "POS exports",
        body: "Sales reports from your current system",
      },
      {
        icon: "🗂️",
        title: "CSV files",
        body: "Simple spreadsheets your team already has",
      },
      {
        icon: "📦",
        title: "Inventory files",
        body: "Stock counts and product reports",
      },
    ],
    resultsTitle: "What you get",
    results: [
      "We clean and organize your data.",
      "We show what needs attention.",
      "You get a simple daily view.",
    ],
    note: "No training needed",
  },
  pricing: {
    eyebrow: "Pricing",
    titleStart: "Try it free.",
    titleAccent: "See the results",
    lead: "Reduce waste and avoid empty shelves before you pay.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "For one store that wants a clearer view of sales and stock.",
        list: [
          "Executive, sales, and inventory dashboards",
          "Stockout predictions for all products",
          "Up to 500 products",
          "Daily data refresh",
          "Email alerts",
          "No multi-store view",
          "No demand forecasting",
        ],
        cta: "Get Started Free",
      },
      {
        tier: "Growth",
        badge: "Most Popular",
        price: "€149",
        description: "For stores with more products, more staff, or more than one location.",
        list: [
          "Everything in Starter",
          "Up to 3 stores in one view",
          "Up to 2,000 products",
          "Waste and expiry risk scoring",
          "14-day demand forecast",
          "Price sensitivity signals",
          "No white-label or API",
        ],
        cta: "Book a Demo",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Custom",
        description: "For larger businesses and partners who need a custom setup.",
        list: [
          "Unlimited stores and products",
          "White-label option",
          "API access",
          "Anonymous benchmarking",
          "Dedicated onboarding",
          "Priority support",
        ],
        cta: "Talk to Us",
      },
    ],
  },
  cta: {
    eyebrow: "Book a Demo",
    titleStart: "See what is happening",
    titleAccent: "in your store",
    body: "Book a short demo and find where you are losing money.",
  },
  legal: {
    privacy: {
      title: "Privacy Policy",
      lead: "This Privacy Policy explains how Shelf8 collects and uses information when you browse the site or book a demo call.",
      sections: [
        { title: "Information We Collect", body: "We may collect contact details you submit, booking information, browser metadata, and high-level usage analytics needed to run the site." },
        { title: "How We Use Information", body: "We use submitted data to respond to inquiries, schedule demos, improve the site, and communicate about our services." },
        { title: "Calendly and Third Parties", body: "When you book a demo, your information may also be processed by third-party scheduling, video, analytics, and hosting providers." },
        { title: "Data Retention", body: "We keep information only for as long as reasonably necessary to operate the site, manage conversations, and meet legal obligations." },
        { title: "Your Rights", body: "You can request access, correction, or deletion of personal information by contacting us at hello@shelf8.com." },
        { title: "Contact", body: "Questions about privacy can be sent to hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Terms of Use",
      lead: "These Terms of Use govern access to the Shelf8 website and any demo booking made through it.",
      sections: [
        { title: "Website Use", body: "You may use this site for lawful business purposes only and may not interfere with its security or availability." },
        { title: "Content", body: "All branding, copy, visuals, and materials on this site belong to Shelf8 unless stated otherwise and may not be reused without permission." },
        { title: "Demo Bookings", body: "Demo availability is subject to change. We may reschedule or decline a meeting if the requested slot becomes unavailable." },
        { title: "No Commercial Guarantee", body: "Information on this site is provided for general informational purposes and does not guarantee any commercial outcome." },
        { title: "Liability", body: "To the fullest extent permitted by law, Shelf8 is not liable for indirect or consequential losses arising from use of this website." },
        { title: "Contact", body: "Questions about these terms can be sent to hello@shelf8.com." },
      ],
    },
  },
};

const sr = {
  meta: {
    landingTitle: "Shelf8 | Retail analitika za prehrambene prodavnice",
    landingDescription:
      "Shelf8 pomaže prodavnicama da prodaju više, manje bacaju robu, drže rafove punim i svakog dana donose jasnije odluke.",
    privacyTitle: "Politika privatnosti | Shelf8",
    privacyDescription: "Kako Shelf8 prikuplja, koristi i štiti podatke sa sajta i rezervacija poziva.",
    termsTitle: "Uslovi korišćenja | Shelf8",
    termsDescription: "Uslovi koji uređuju korišćenje Shelf8 sajta i rezervaciju demo poziva.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Zakaži demo",
    seeHowItWorks: "Pogledaj kako radi",
    allRightsReserved: "Sva prava zadržana.",
    menu: "Meni",
    close: "Zatvori",
    freeBadge: "Prva 3 meseca besplatno",
    monthAfter: "/ mesečno nakon toga",
    backHome: "Nazad na početnu",
    updated: "Poslednje ažuriranje",
  },
  nav: {
    howItWorks: "Kako radi",
    examples: "Primeri",
    benefits: "Ključne prednosti",
    pricing: "Cene",
    privacy: "Politika privatnosti",
    terms: "Uslovi korišćenja",
  },
  hero: {
    eyebrow: "Za prehrambene prodavnice i retail timove",
    titleStart: "Bacajte manje hrane.",
    titleMiddle: "Neka rafovi budu puni.",
    titleAccent: "Povećajte prodaju.",
    subtitle:
      "Vidite šta se prodaje, šta usporava, šta treba poručiti i šta može da završi kao otpad.",
    metrics: [
      { label: "Prihod MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Bruto marža", value: "34.6%" },
      { label: "Obrt zaliha", value: "3.2×", note: "Stabilno" },
    ],
    chartTitle: "Prihod po kategoriji · 30 dana",
    categories: [
      { label: "Pića", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Mlečni proizvodi", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Riba", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "Meso", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Prognoza nestanka zaliha",
    stockouts: [
      { name: "Jaja 12 kom", meta: "Mlečni proizvodi · 40 kom", status: "1.9d · Kritično", tone: "danger" },
      { name: "Cheddar sir 200g", meta: "Mlečni proizvodi · 55 kom", status: "6.4d · Upozorenje", tone: "warning" },
      { name: "Mleko 1L", meta: "Mlečni proizvodi · 35 kom", status: "17.5d · OK", tone: "success" },
      { name: "Hleb od kiselog testa", meta: "Pekara · 143 kom", status: "7.9d · OK", tone: "success" },
      { name: "Grčki jogurt 500g", meta: "Mlečni proizvodi · 93 kom", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "Kako radi",
    titleStart: "Otpremite svoje podatke.",
    titleAccent: "Vidite šta treba popraviti",
    lead: "Pošaljite izveštaje ili fajlove. Pokazujemo šta treba poručiti, šta treba pratiti i gde novac curi.",
    steps: [
      { icon: "🔗", title: "Otpremi", body: "Otpremite račune ili izveštaje." },
      { icon: "⚙️", title: "Organizuj", body: "Sve organizujemo." },
      { icon: "🧠", title: "Vidi probleme", body: "Vidite probleme u zalihama." },
      { icon: "📊", title: "Reaguj", body: "Znate šta sledeće treba popraviti." },
    ],
  },
  benefits: {
    eyebrow: "Ključne prednosti",
    titleStart: "Sve što treba da vidite",
    titleAccent: "u Shelf8",
    inventory: {
      tag: "Zalihe",
      titleStart: "Neka rafovi budu",
      titleAccent: "puni",
      body: "Vidite šta nestaje i poručite pre nego što kupci primete.",
      list: [
        "Na vreme uočite nizak lager",
        "Izbegnite prazne rafove",
        "Pratite vrednost zaliha",
        "Znajte šta se brzo prodaje",
      ],
      screenLabel: "Zalihe",
      topCards: [
        { label: "Na stanju", value: "7.0K" },
        { label: "Vrednost zaliha", value: "€31.2K" },
        { label: "Aktivni SKU", value: "1.5K" },
      ],
      panelTitle: "Proizvodi kojima treba pažnja",
      rows: [
        { label: "Jaja 12 kom", status: "1.9d · Kritično", tone: "danger" },
        { label: "Cheddar sir 200g", status: "6.4d · Upozorenje", tone: "warning" },
        { label: "Mleko 1L", status: "17.5d · OK", tone: "success" },
        { label: "Organske banane", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Prodaja",
      titleStart: "Znajte šta se zaista",
      titleAccent: "prodaje",
      body: "Vidite koji proizvodi donose novac, a koji samo zauzimaju mesto.",
      list: [
        "Vidite top proizvode",
        "Prepoznajte spore artikle",
        "Pratite prihod i maržu",
      ],
      screenLabel: "Prodaja",
      topCards: [
        { label: "Ukupan prihod", value: "€25.6K" },
        { label: "Bruto profit", value: "€14.4K", tone: "success" },
        { label: "Bruto marža", value: "56.3%" },
      ],
      panelTitle: "Najprodavaniji proizvodi",
      rows: [
        { label: "Avokado", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Espresso kafa", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Pasta", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Losos", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Upozorenja",
      titleStart: "Rešite probleme pre nego što",
      titleAccent: "vas koštaju",
      body: "Vidite gde gubite novac i šta da uradite povodom toga.",
      list: [],
      screenLabel: "Upozorenja",
      notices: [
        { icon: "📉", title: "Izgubljena prodaja", body: "Proizvodi nisu na stanju — propuštate prihod.", tone: "danger-soft" },
        { icon: "⚠️", title: "Rizik od isteka", body: "Neki artikli se neće prodati pre isteka roka.", tone: "warning-soft" },
        { icon: "💡", title: "Prilika za cenu", body: "Male promene cene mogu da povećaju prihod.", tone: "success-soft" },
      ],
    },
  },
  examples: {
    eyebrow: "Primeri",
    titleStart: "Vidite šta danas traži",
    titleAccent: "reakciju",
    lead: "",
    cards: [
      {
        title: "Mleka može nestati za 2 dana",
        body: "Poručite pre nego što raf ostane prazan.",
        icon: "🥛",
        badge: "LOW",
      },
      {
        title: "Jogurt se slabo prodaje",
        body: "Poručujte manje ili ga dodatno istaknite.",
        icon: "🥣",
        badge: "SLOW",
      },
      {
        title: "Jaja se brzo prodaju, sira nema",
        body: "Popravite taj raskorak u zalihama.",
        icon: "🥚",
        badge: "GAP",
      },
      {
        title: "Otpad iz pekare raste ove nedelje",
        body: "Reagujte pre nego što se izgubi još robe.",
        icon: "🥐",
        badge: "WASTE",
      },
    ],
  },
  trust: {
    eyebrow: "Podešavanje",
    titleStart: "Koristite podatke",
    titleAccent: "koje već imate",
    lead: "Bez komplikovanog podešavanja. Pošaljite fajlove i dobijte jasan pregled svoje prodavnice.",
    sourcesTitle: "Šta možete poslati",
    sources: [
      {
        icon: "🧾",
        title: "Računi",
        body: "Fiskalni računi ili izvoz računa",
      },
      {
        icon: "📊",
        title: "POS izveštaji",
        body: "Izveštaji o prodaji iz vašeg sistema",
      },
      {
        icon: "🗂️",
        title: "CSV fajlovi",
        body: "Jednostavne tabele koje vaš tim već ima",
      },
      {
        icon: "📦",
        title: "Fajlovi o zalihama",
        body: "Popisi stanja i izveštaji o proizvodima",
      },
    ],
    resultsTitle: "Šta dobijate",
    results: [
      "Čistimo i organizujemo vaše podatke.",
      "Pokazujemo šta traži pažnju.",
      "Dobijate jednostavan dnevni pregled.",
    ],
    note: "Nije potrebna obuka",
  },
  pricing: {
    eyebrow: "Cene",
    titleStart: "Probajte besplatno.",
    titleAccent: "Pogledajte rezultate",
    lead: "Smanjite otpad i izbegnite prazne rafove pre nego što počnete da plaćate.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "Za jednu prodavnicu kojoj treba jasniji pregled prodaje i zaliha.",
        list: [
          "Pregledni dashboardi za prodaju i zalihe",
          "Predikcija nestanka zaliha za sve proizvode",
          "Do 500 proizvoda",
          "Dnevno osvežavanje podataka",
          "Email upozorenja",
          "Bez prikaza više lokacija",
          "Bez prognoze tražnje",
        ],
        cta: "Počni besplatno",
      },
      {
        tier: "Growth",
        badge: "Najpopularniji",
        price: "€149",
        description: "Za prodavnice sa više proizvoda, više zaposlenih ili više lokacija.",
        list: [
          "Sve iz Starter paketa",
          "Do 3 radnje u jednom prikazu",
          "Do 2.000 proizvoda",
          "Skorovi otpada i isteka",
          "14-dnevna prognoza tražnje",
          "Signali osetljivosti cene",
          "Bez white-label i API opcije",
        ],
        cta: "Zakaži demo",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Prilagođeno",
        description: "Za veće firme i partnere kojima treba prilagođeno rešenje.",
        list: [
          "Neograničen broj radnji i proizvoda",
          "White-label opcija",
          "API pristup",
          "Anonimni benchmarking",
          "Posvećen onboarding",
          "Prioritetna podrška",
        ],
        cta: "Kontaktiraj nas",
      },
    ],
  },
  cta: {
    eyebrow: "Zakažite demo",
    titleStart: "Vidite šta se dešava",
    titleAccent: "u vašoj prodavnici",
    body: "Zakažite kratak demo i saznajte gde gubite novac.",
  },
  legal: {
    privacy: {
      title: "Politika privatnosti",
      lead: "Ova Politika privatnosti objašnjava kako Shelf8 prikuplja i koristi podatke kada pregledate sajt ili zakažete demo poziv.",
      sections: [
        { title: "Koje podatke prikupljamo", body: "Možemo prikupljati kontakt podatke koje pošaljete, informacije o rezervaciji, metapodatke pregledača i osnovnu analitiku korišćenja sajta." },
        { title: "Kako koristimo podatke", body: "Podatke koristimo da odgovorimo na upite, zakažemo demo, unapredimo sajt i komuniciramo o našim uslugama." },
        { title: "Calendly i treće strane", body: "Kada zakažete demo, vaše informacije mogu obrađivati i provajderi za zakazivanje, video pozive, analitiku i hosting." },
        { title: "Čuvanje podataka", body: "Podatke čuvamo samo onoliko dugo koliko je razumno potrebno za rad sajta, vođenje komunikacije i ispunjavanje zakonskih obaveza." },
        { title: "Vaša prava", body: "Možete tražiti pristup, ispravku ili brisanje ličnih podataka kontaktiranjem na hello@shelf8.com." },
        { title: "Kontakt", body: "Pitanja o privatnosti možete poslati na hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Uslovi korišćenja",
      lead: "Ovi Uslovi korišćenja uređuju pristup Shelf8 sajtu i svaku demo rezervaciju napravljenu preko njega.",
      sections: [
        { title: "Korišćenje sajta", body: "Sajt možete koristiti samo u zakonite poslovne svrhe i ne smete ometati njegovu bezbednost ili dostupnost." },
        { title: "Sadržaj", body: "Brending, tekstovi, vizuali i materijali na ovom sajtu pripadaju Shelf8 osim ako nije drugačije navedeno i ne smeju se koristiti bez dozvole." },
        { title: "Demo rezervacije", body: "Dostupnost termina može se menjati. Možemo pomeriti ili odbiti sastanak ako izabrani termin više nije dostupan." },
        { title: "Bez poslovne garancije", body: "Informacije na sajtu služe opštem informisanju i ne garantuju bilo kakav komercijalni rezultat." },
        { title: "Odgovornost", body: "U meri dopuštenoj zakonom, Shelf8 ne odgovara za posredne ili posledične gubitke nastale korišćenjem ovog sajta." },
        { title: "Kontakt", body: "Pitanja o ovim uslovima pošaljite na hello@shelf8.com." },
      ],
    },
  },
};

const de = {
  meta: {
    landingTitle: "Shelf8 | Retail-Analytik fuer Lebensmittelhaendler",
    landingDescription:
      "Shelf8 hilft Laeden, mehr zu verkaufen, weniger Ware zu verlieren, Regale voll zu halten und taeglich klarere Entscheidungen zu treffen.",
    privacyTitle: "Datenschutzerklaerung | Shelf8",
    privacyDescription: "Wie Shelf8 Website- und Buchungsdaten erhebt, nutzt und schuetzt.",
    termsTitle: "Nutzungsbedingungen | Shelf8",
    termsDescription: "Die Bedingungen fuer die Nutzung der Shelf8 Website und gebuchte Demo-Termine.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Demo buchen",
    seeHowItWorks: "So funktioniert es",
    allRightsReserved: "Alle Rechte vorbehalten.",
    menu: "Menue",
    close: "Schliessen",
    freeBadge: "Die ersten 3 Monate kostenlos",
    monthAfter: "/ Monat danach",
    backHome: "Zur Startseite",
    updated: "Zuletzt aktualisiert",
  },
  nav: {
    howItWorks: "So funktioniert es",
    examples: "Beispiele",
    benefits: "Vorteile",
    pricing: "Preise",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
  },
  hero: {
    eyebrow: "Fuer Lebensmittelgeschaefte und Retail-Teams",
    titleStart: "Weniger Lebensmittel verschwenden.",
    titleMiddle: "Regale voll halten.",
    titleAccent: "Mehr verkaufen.",
    subtitle:
      "Sehen Sie, was gut laeuft, was liegen bleibt, was nachbestellt werden muss und was zu Abschriften werden kann.",
    metrics: [
      { label: "Umsatz MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Bruttomarge", value: "34.6%" },
      { label: "Lagerumschlag", value: "3.2×", note: "Stabil" },
    ],
    chartTitle: "Umsatz nach Kategorie · 30 Tage",
    categories: [
      { label: "Getraenke", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Molkerei", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Fisch", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "Fleisch", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Out-of-Stock-Prognosen",
    stockouts: [
      { name: "Freilandeier 12er", meta: "Molkerei · 40 Stk", status: "1.9d · Kritisch", tone: "danger" },
      { name: "Cheddar 200g", meta: "Molkerei · 55 Stk", status: "6.4d · Warnung", tone: "warning" },
      { name: "Vollmilch 1L", meta: "Molkerei · 35 Stk", status: "17.5d · OK", tone: "success" },
      { name: "Sauerteigbrot", meta: "Backwaren · 143 Stk", status: "7.9d · OK", tone: "success" },
      { name: "Griechischer Joghurt 500g", meta: "Molkerei · 93 Stk", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "So funktioniert es",
    titleStart: "Laden Sie Ihre Daten hoch.",
    titleAccent: "Sehen Sie, was korrigiert werden muss",
    lead: "Senden Sie Ihre Berichte oder Dateien. Wir zeigen, was nachbestellt werden muss, was beobachtet werden sollte und wo Geld verloren geht.",
    steps: [
      { icon: "🔗", title: "Hochladen", body: "Laden Sie Kassenbons oder Berichte hoch." },
      { icon: "⚙️", title: "Ordnen", body: "Wir ordnen alles fuer Sie." },
      { icon: "🧠", title: "Probleme sehen", body: "Erkennen Sie Probleme im Bestand." },
      { icon: "📊", title: "Handeln", body: "Sie wissen, was Sie als Naechstes beheben muessen." },
    ],
  },
  benefits: {
    eyebrow: "Vorteile",
    titleStart: "Alles, was Sie sehen koennen",
    titleAccent: "in Shelf8",
    inventory: {
      tag: "Bestand",
      titleStart: "Regale voll",
      titleAccent: "halten",
      body: "Sehen Sie, was knapp wird, und bestellen Sie nach, bevor Kunden es merken.",
      list: [
        "Niedrige Bestaende frueh erkennen",
        "Leere Regale vermeiden",
        "Bestandswert verfolgen",
        "Sehen, was sich schnell verkauft",
      ],
      screenLabel: "Bestand",
      topCards: [
        { label: "Bestand", value: "7.0K" },
        { label: "Bestandswert", value: "€31.2K" },
        { label: "Aktive SKU", value: "1.5K" },
      ],
      panelTitle: "Produkte mit Handlungsbedarf",
      rows: [
        { label: "Freilandeier 12er", status: "1.9d · Kritisch", tone: "danger" },
        { label: "Cheddar 200g", status: "6.4d · Warnung", tone: "warning" },
        { label: "Vollmilch 1L", status: "17.5d · OK", tone: "success" },
        { label: "Bio-Bananen", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Verkauf",
      titleStart: "Sehen Sie, was sich",
      titleAccent: "wirklich verkauft",
      body: "Sehen Sie, welche Produkte Geld bringen und welche nur Platz im Regal einnehmen.",
      list: [
        "Top-Produkte sehen",
        "Langsamdreher erkennen",
        "Umsatz und Marge verfolgen",
      ],
      screenLabel: "Verkauf",
      topCards: [
        { label: "Gesamtumsatz", value: "€25.6K" },
        { label: "Bruttogewinn", value: "€14.4K", tone: "success" },
        { label: "Bruttomarge", value: "56.3%" },
      ],
      panelTitle: "Top-Seller",
      rows: [
        { label: "Avocado", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Espressobohnen", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Pasta", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Lachs", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Alerts",
      titleStart: "Probleme loesen, bevor",
      titleAccent: "sie Geld kosten",
      body: "Sehen Sie, wo Geld verloren geht und was Sie dagegen tun koennen.",
      list: [],
      screenLabel: "Alerts",
      notices: [
        { icon: "📉", title: "Verlorener Umsatz", body: "Produkte sind nicht auf Lager — dadurch geht Umsatz verloren.", tone: "danger-soft" },
        { icon: "⚠️", title: "Ablaufrisiko", body: "Einige Artikel werden sich vor dem Ablaufdatum nicht verkaufen.", tone: "warning-soft" },
        { icon: "💡", title: "Preis-Chance", body: "Kleine Preisveraenderungen koennen den Umsatz steigern.", tone: "success-soft" },
      ],
    },
  },
  examples: {
    eyebrow: "Beispiele",
    titleStart: "Sehen Sie, was heute",
    titleAccent: "Handlung braucht",
    lead: "",
    cards: [
      {
        title: "Milch ist in 2 Tagen leer",
        body: "Jetzt nachbestellen, bevor das Regal leer ist.",
        icon: "🥛",
        badge: "LOW",
      },
      {
        title: "Joghurt verkauft sich zu langsam",
        body: "Weniger bestellen oder gezielt bewerben.",
        icon: "🥣",
        badge: "SLOW",
      },
      {
        title: "Eier laufen gut, Kaese fehlt oft",
        body: "Diese Luecke im Bestand schliessen.",
        icon: "🥚",
        badge: "GAP",
      },
      {
        title: "Der Verderb bei Backwaren steigt",
        body: "Handeln, bevor noch mehr verloren geht.",
        icon: "🥐",
        badge: "WASTE",
      },
    ],
  },
  trust: {
    eyebrow: "Setup",
    titleStart: "Nutzen Sie die Daten,",
    titleAccent: "die Sie schon haben",
    lead: "Kein aufwendiges Setup. Senden Sie Ihre Dateien und bekommen Sie einen klaren Blick auf Ihr Geschaeft.",
    sourcesTitle: "Was Sie senden koennen",
    sources: [
      {
        icon: "🧾",
        title: "Kassenbons",
        body: "Kassenbons oder Kassenexporte",
      },
      {
        icon: "📊",
        title: "POS-Exporte",
        body: "Verkaufsberichte aus Ihrem System",
      },
      {
        icon: "🗂️",
        title: "CSV-Dateien",
        body: "Einfache Tabellen, die Ihr Team schon nutzt",
      },
      {
        icon: "📦",
        title: "Bestandsdateien",
        body: "Bestandszaehlungen und Artikelberichte",
      },
    ],
    resultsTitle: "Was Sie bekommen",
    results: [
      "Wir bereinigen und ordnen Ihre Daten.",
      "Wir zeigen, was Aufmerksamkeit braucht.",
      "Sie bekommen einen einfachen taeglichen Ueberblick.",
    ],
    note: "Keine Schulung noetig",
  },
  pricing: {
    eyebrow: "Preise",
    titleStart: "Kostenlos testen.",
    titleAccent: "Ergebnisse sehen",
    lead: "Weniger Verderb und weniger leere Regale, noch bevor Sie bezahlen.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "Fuer einen Standort, der einen klareren Blick auf Verkauf und Bestand braucht.",
        list: [
          "Dashboards fuer Verkauf und Bestand",
          "Stockout-Prognosen fuer alle Produkte",
          "Bis zu 500 Produkte",
          "Taegliche Datenaktualisierung",
          "E-Mail-Alerts",
          "Kein Multi-Store-Blick",
          "Keine Nachfrageprognose",
        ],
        cta: "Kostenlos starten",
      },
      {
        tier: "Growth",
        badge: "Meistgewaehlt",
        price: "€149",
        description: "Fuer Geschaefte mit mehr Produkten, mehr Mitarbeitenden oder mehr als einem Standort.",
        list: [
          "Alles aus Starter",
          "Bis zu 3 Standorte in einer Sicht",
          "Bis zu 2.000 Produkte",
          "Scores fuer Verderb und Ablauf",
          "14-Tage-Nachfrageprognose",
          "Preissensitivitaetssignale",
          "Kein White-Label oder API",
        ],
        cta: "Demo buchen",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Individuell",
        description: "Fuer groessere Unternehmen und Partner mit individuellem Bedarf.",
        list: [
          "Unbegrenzte Standorte und Produkte",
          "White-Label-Option",
          "API-Zugang",
          "Anonymes Benchmarking",
          "Dediziertes Onboarding",
          "Priorisierter Support",
        ],
        cta: "Kontakt",
      },
    ],
  },
  cta: {
    eyebrow: "Demo buchen",
    titleStart: "Sehen Sie, was in Ihrem",
    titleAccent: "Geschaeft passiert",
    body: "Buchen Sie eine kurze Demo und sehen Sie, wo Geld verloren geht.",
  },
  legal: {
    privacy: {
      title: "Datenschutzerklaerung",
      lead: "Diese Datenschutzerklaerung erklaert, wie Shelf8 Daten erhebt und nutzt, wenn Sie die Website besuchen oder eine Demo buchen.",
      sections: [
        { title: "Welche Daten wir erfassen", body: "Wir koennen Kontaktdaten, Buchungsinformationen, Browser-Metadaten und grundlegende Nutzungsanalysen erfassen." },
        { title: "Wie wir Daten nutzen", body: "Wir nutzen Daten, um auf Anfragen zu reagieren, Demos zu planen, die Website zu verbessern und ueber unsere Services zu kommunizieren." },
        { title: "Calendly und Drittanbieter", body: "Wenn Sie eine Demo buchen, koennen Ihre Daten auch von Termin-, Video-, Analyse- und Hosting-Anbietern verarbeitet werden." },
        { title: "Speicherdauer", body: "Wir speichern Daten nur so lange, wie es fuer Betrieb, Kommunikation und gesetzliche Pflichten angemessen erforderlich ist." },
        { title: "Ihre Rechte", body: "Sie koennen Zugang, Berichtigung oder Loeschung personenbezogener Daten ueber hello@shelf8.com anfordern." },
        { title: "Kontakt", body: "Fragen zum Datenschutz senden Sie bitte an hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Nutzungsbedingungen",
      lead: "Diese Nutzungsbedingungen regeln den Zugriff auf die Shelf8 Website und jede darueber gebuchte Demo.",
      sections: [
        { title: "Nutzung der Website", body: "Sie duerfen diese Website nur fuer rechtmaessige geschaeftliche Zwecke nutzen und ihre Sicherheit oder Verfuegbarkeit nicht beeintraechtigen." },
        { title: "Inhalte", body: "Marke, Texte, Visuals und Materialien auf dieser Website gehoeren Shelf8, sofern nicht anders angegeben, und duerfen nicht ohne Erlaubnis wiederverwendet werden." },
        { title: "Demo-Buchungen", body: "Verfuegbare Termine koennen sich aendern. Wir koennen Meetings verschieben oder ablehnen, wenn ein Slot nicht mehr verfuegbar ist." },
        { title: "Keine kommerzielle Garantie", body: "Die Informationen auf dieser Website dienen allgemeinen Informationszwecken und garantieren kein wirtschaftliches Ergebnis." },
        { title: "Haftung", body: "Soweit gesetzlich zulaessig, haftet Shelf8 nicht fuer indirekte oder Folgeschaeden aus der Nutzung dieser Website." },
        { title: "Kontakt", body: "Fragen zu diesen Bedingungen senden Sie bitte an hello@shelf8.com." },
      ],
    },
  },
};

const uk = {
  meta: {
    landingTitle: "Shelf8 | Retail-аналітика для продуктових магазинів",
    landingDescription:
      "Shelf8 допомагає магазинам більше продавати, менше втрачати товар, тримати полиці повними й щодня ухвалювати зрозуміліші рішення.",
    privacyTitle: "Політика конфіденційності | Shelf8",
    privacyDescription: "Як Shelf8 збирає, використовує та захищає дані сайту й бронювань.",
    termsTitle: "Умови використання | Shelf8",
    termsDescription: "Умови, що регулюють використання сайту Shelf8 і бронювання демо-дзвінків.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Забронювати демо",
    seeHowItWorks: "Як це працює",
    allRightsReserved: "Усі права захищено.",
    menu: "Меню",
    close: "Закрити",
    freeBadge: "Перші 3 місяці безкоштовно",
    monthAfter: "/ місяць після цього",
    backHome: "Назад на головну",
    updated: "Оновлено",
  },
  nav: {
    howItWorks: "Як це працює",
    examples: "Приклади",
    benefits: "Ключові переваги",
    pricing: "Ціни",
    privacy: "Політика конфіденційності",
    terms: "Умови використання",
  },
  hero: {
    eyebrow: "Для продуктових магазинів і retail-команд",
    titleStart: "Менше списань.",
    titleMiddle: "Повні полиці.",
    titleAccent: "Більше продажів.",
    subtitle:
      "Бачте, що продається, що сповільнюється, що треба дозамовити і що може піти у списання.",
    metrics: [
      { label: "Дохід MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Валова маржа", value: "34.6%" },
      { label: "Оборот запасів", value: "3.2×", note: "Стабільно" },
    ],
    chartTitle: "Дохід за категоріями · 30 днів",
    categories: [
      { label: "Напої", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Молочні продукти", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Риба", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "М'ясо", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Прогноз відсутності товару",
    stockouts: [
      { name: "Яйця 12 шт", meta: "Молочні продукти · 40 шт", status: "1.9d · Критично", tone: "danger" },
      { name: "Сир cheddar 200g", meta: "Молочні продукти · 55 шт", status: "6.4d · Увага", tone: "warning" },
      { name: "Молоко 1L", meta: "Молочні продукти · 35 шт", status: "17.5d · OK", tone: "success" },
      { name: "Хліб на заквасці", meta: "Пекарня · 143 шт", status: "7.9d · OK", tone: "success" },
      { name: "Грецький йогурт 500g", meta: "Молочні продукти · 93 шт", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "Як це працює",
    titleStart: "Завантажте свої дані.",
    titleAccent: "Побачте, що треба виправити",
    lead: "Надішліть звіти або файли. Ми покажемо, що треба замовити, що варто контролювати і де ви втрачаєте гроші.",
    steps: [
      { icon: "🔗", title: "Завантажити", body: "Завантажте чеки або звіти." },
      { icon: "⚙️", title: "Упорядкувати", body: "Ми все впорядковуємо." },
      { icon: "🧠", title: "Побачити проблеми", body: "Побачте проблеми у запасах." },
      { icon: "📊", title: "Діяти", body: "Зрозумійте, що треба виправити далі." },
    ],
  },
  benefits: {
    eyebrow: "Ключові переваги",
    titleStart: "Усе, що ви бачите",
    titleAccent: "в Shelf8",
    inventory: {
      tag: "Запаси",
      titleStart: "Тримайте полиці",
      titleAccent: "повними",
      body: "Бачте, що закінчується, і дозамовляйте до того, як це помітять покупці.",
      list: [
        "Завчасно ловіть низький залишок",
        "Уникайте порожніх полиць",
        "Відстежуйте вартість запасів",
        "Знайте, що продається швидко",
      ],
      screenLabel: "Запаси",
      topCards: [
        { label: "У наявності", value: "7.0K" },
        { label: "Вартість запасів", value: "€31.2K" },
        { label: "Активні SKU", value: "1.5K" },
      ],
      panelTitle: "Товари, яким потрібна увага",
      rows: [
        { label: "Яйця 12 шт", status: "1.9d · Критично", tone: "danger" },
        { label: "Сир cheddar 200g", status: "6.4d · Увага", tone: "warning" },
        { label: "Молоко 1L", status: "17.5d · OK", tone: "success" },
        { label: "Органічні банани", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Продажі",
      titleStart: "Знайте, що справді",
      titleAccent: "продається",
      body: "Бачте, які товари приносять гроші, а які лише займають місце.",
      list: [
        "Бачте топ-товари",
        "Знаходьте повільні позиції",
        "Відстежуйте дохід і маржу",
      ],
      screenLabel: "Продажі",
      topCards: [
        { label: "Загальний дохід", value: "€25.6K" },
        { label: "Валовий прибуток", value: "€14.4K", tone: "success" },
        { label: "Валова маржа", value: "56.3%" },
      ],
      panelTitle: "Найкращі продажі",
      rows: [
        { label: "Авокадо", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Кава еспресо", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Паста", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Лосось", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Попередження",
      titleStart: "Вирішуйте проблеми до того, як",
      titleAccent: "вони коштуватимуть вам грошей",
      body: "Бачте, де ви втрачаєте гроші і що з цим робити.",
      list: [],
      screenLabel: "Попередження",
      notices: [
        { icon: "📉", title: "Втрачений дохід", body: "Товарів немає в наявності — ви втрачаєте виручку.", tone: "danger-soft" },
        { icon: "⚠️", title: "Ризик списання", body: "Деякі товари не продадуться до завершення терміну придатності.", tone: "warning-soft" },
        { icon: "💡", title: "Цінова можливість", body: "Невеликі зміни ціни можуть збільшити дохід.", tone: "success-soft" },
      ],
    },
  },
  examples: {
    eyebrow: "Приклади",
    titleStart: "Бачте, що сьогодні потребує",
    titleAccent: "дії",
    lead: "",
    cards: [
      {
        title: "Молоко закінчиться за 2 дні",
        body: "Дозамовте до того, як полиця спорожніє.",
        icon: "🥛",
        badge: "LOW",
      },
      {
        title: "Йогурт не продається",
        body: "Замовляйте менше або просувайте його активніше.",
        icon: "🥣",
        badge: "SLOW",
      },
      {
        title: "Яйця продаються швидко, сиру не вистачає",
        body: "Закрийте цей розрив у запасах.",
        icon: "🥚",
        badge: "GAP",
      },
      {
        title: "Списання випічки зростає цього тижня",
        body: "Дійте, поки втрати не стали більшими.",
        icon: "🥐",
        badge: "WASTE",
      },
    ],
  },
  trust: {
    eyebrow: "Налаштування",
    titleStart: "Використовуйте дані,",
    titleAccent: "які вже маєте",
    lead: "Без складного налаштування. Надішліть свої файли й отримайте зрозумілий огляд магазину.",
    sourcesTitle: "Що можна надіслати",
    sources: [
      {
        icon: "🧾",
        title: "Чеки",
        body: "Фіскальні чеки або їх експорт",
      },
      {
        icon: "📊",
        title: "POS-експорт",
        body: "Звіти про продажі з вашої поточної системи",
      },
      {
        icon: "🗂️",
        title: "CSV-файли",
        body: "Прості таблиці, які вже є у вашої команди",
      },
      {
        icon: "📦",
        title: "Файли запасів",
        body: "Інвентаризації та звіти по товарах",
      },
    ],
    resultsTitle: "Що ви отримуєте",
    results: [
      "Ми очищаємо й упорядковуємо ваші дані.",
      "Ми показуємо, що потребує уваги.",
      "Ви отримуєте простий щоденний огляд.",
    ],
    note: "Навчання не потрібне",
  },
  pricing: {
    eyebrow: "Ціни",
    titleStart: "Спробуйте безкоштовно.",
    titleAccent: "Побачте результат",
    lead: "Зменшуйте списання й уникайте порожніх полиць до того, як почнете платити.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "Для одного магазину, якому потрібен зрозуміліший огляд продажів і запасів.",
        list: [
          "Дашборди для продажів і запасів",
          "Прогноз відсутності товару для всіх позицій",
          "До 500 товарів",
          "Щоденне оновлення даних",
          "Email-сповіщення",
          "Без перегляду кількох магазинів",
          "Без прогнозу попиту",
        ],
        cta: "Почати безкоштовно",
      },
      {
        tier: "Growth",
        badge: "Найпопулярніший",
        price: "€149",
        description: "Для магазинів із більшою кількістю товарів, працівників або локацій.",
        list: [
          "Усе зі Starter",
          "До 3 магазинів в одному перегляді",
          "До 2 000 товарів",
          "Скоринг списання та закінчення терміну",
          "14-денний прогноз попиту",
          "Сигнали цінової чутливості",
          "Без white-label та API",
        ],
        cta: "Забронювати демо",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Custom",
        description: "Для більших компаній і партнерів, яким потрібне індивідуальне налаштування.",
        list: [
          "Необмежена кількість магазинів і товарів",
          "Опція white-label",
          "Доступ до API",
          "Анонімний бенчмаркінг",
          "Окремий онбординг",
          "Пріоритетна підтримка",
        ],
        cta: "Зв'язатися",
      },
    ],
  },
  cta: {
    eyebrow: "Забронювати демо",
    titleStart: "Побачте, що відбувається",
    titleAccent: "у вашому магазині",
    body: "Забронюйте коротке демо й знайдіть, де ви втрачаєте гроші.",
  },
  legal: {
    privacy: {
      title: "Політика конфіденційності",
      lead: "Ця Політика конфіденційності пояснює, як Shelf8 збирає та використовує дані, коли ви переглядаєте сайт або бронюєте демо.",
      sections: [
        { title: "Які дані ми збираємо", body: "Ми можемо збирати контактні дані, інформацію про бронювання, метадані браузера та базову аналітику використання сайту." },
        { title: "Як ми використовуємо дані", body: "Ми використовуємо дані, щоб відповідати на запити, планувати демо, покращувати сайт і комунікувати щодо наших послуг." },
        { title: "Calendly і треті сторони", body: "Коли ви бронюєте демо, ваші дані також можуть оброблятися сервісами бронювання, відеозв'язку, аналітики й хостингу." },
        { title: "Зберігання даних", body: "Ми зберігаємо дані лише стільки, скільки розумно необхідно для роботи сайту, комунікації та виконання юридичних обов'язків." },
        { title: "Ваші права", body: "Ви можете запросити доступ, виправлення або видалення персональних даних через hello@shelf8.com." },
        { title: "Контакт", body: "Питання щодо конфіденційності надсилайте на hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Умови використання",
      lead: "Ці Умови використання регулюють доступ до сайту Shelf8 і кожне демо-бронювання, зроблене через нього.",
      sections: [
        { title: "Використання сайту", body: "Ви можете використовувати цей сайт лише для законних бізнес-цілей і не повинні порушувати його безпеку чи доступність." },
        { title: "Контент", body: "Брендинг, тексти, візуали та матеріали на цьому сайті належать Shelf8, якщо не зазначено інше, і не можуть використовуватись без дозволу." },
        { title: "Бронювання демо", body: "Доступність слотів може змінюватися. Ми можемо перенести або скасувати зустріч, якщо вибраний час більше недоступний." },
        { title: "Без комерційних гарантій", body: "Інформація на сайті надається для загального ознайомлення і не гарантує будь-якого комерційного результату." },
        { title: "Відповідальність", body: "У межах, дозволених законом, Shelf8 не несе відповідальності за непрямі або побічні збитки, пов'язані з використанням сайту." },
        { title: "Контакт", body: "Питання щодо цих умов надсилайте на hello@shelf8.com." },
      ],
    },
  },
};

const he = {
  meta: {
    landingTitle: "Shelf8 | אנליטיקה קמעונאית לחנויות מזון",
    landingDescription:
      "Shelf8 עוזרת לחנויות למכור יותר, לבזבז פחות, לשמור על מדפים מלאים ולקבל החלטות יומיות ברורות יותר.",
    privacyTitle: "מדיניות פרטיות | Shelf8",
    privacyDescription: "איך Shelf8 אוספת, משתמשת ומגנה על נתוני אתר והזמנות.",
    termsTitle: "תנאי שימוש | Shelf8",
    termsDescription: "התנאים החלים על השימוש באתר Shelf8 ועל הזמנת שיחות הדגמה.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "קביעת דמו",
    seeHowItWorks: "איך זה עובד",
    allRightsReserved: "כל הזכויות שמורות.",
    menu: "תפריט",
    close: "סגור",
    freeBadge: "3 החודשים הראשונים ללא תשלום",
    monthAfter: "/ לחודש לאחר מכן",
    backHome: "חזרה לדף הבית",
    updated: "עודכן לאחרונה",
  },
  nav: {
    howItWorks: "איך זה עובד",
    examples: "דוגמאות",
    benefits: "יתרונות מרכזיים",
    pricing: "מחירים",
    privacy: "מדיניות פרטיות",
    terms: "תנאי שימוש",
  },
  hero: {
    eyebrow: "לחנויות מזון ולצוותי קמעונאות",
    titleStart: "פחות בזבוז מזון.",
    titleMiddle: "מדפים מלאים.",
    titleAccent: "יותר מכירות.",
    subtitle:
      "ראו מה נמכר, מה נחלש, מה צריך הזמנה מחדש ומה עלול להפוך להפסד.",
    metrics: [
      { label: "הכנסות MTD", value: "€34.6K", note: "+12.0%" },
      { label: "רווח גולמי", value: "34.6%" },
      { label: "מחזור מלאי", value: "3.2×", note: "בריא" },
    ],
    chartTitle: "הכנסות לפי קטגוריה · 30 ימים",
    categories: [
      { label: "משקאות", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "מוצרי חלב", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "דגים", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "בשר", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "תחזית חוסרי מלאי",
    stockouts: [
      { name: "ביצי חופש 12 יח'", meta: "מוצרי חלב · 40 יח'", status: "1.9d · קריטי", tone: "danger" },
      { name: "גבינת צ'דר 200g", meta: "מוצרי חלב · 55 יח'", status: "6.4d · אזהרה", tone: "warning" },
      { name: "חלב 1L", meta: "מוצרי חלב · 35 יח'", status: "17.5d · OK", tone: "success" },
      { name: "לחם מחמצת", meta: "מאפייה · 143 יח'", status: "7.9d · OK", tone: "success" },
      { name: "יוגורט יווני 500g", meta: "מוצרי חלב · 93 יח'", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "איך זה עובד",
    titleStart: "העלו את הנתונים שלכם.",
    titleAccent: "ראו מה צריך תיקון",
    lead: "שלחו דוחות או קבצים. אנחנו מראים מה צריך להזמין מחדש, על מה צריך לעקוב ואיפה הכסף הולך לאיבוד.",
    steps: [
      { icon: "🔗", title: "העלאה", body: "העלו קבלות או דוחות." },
      { icon: "⚙️", title: "סידור", body: "אנחנו מסדרים הכול." },
      { icon: "🧠", title: "זיהוי בעיות", body: "ראו בעיות במלאי." },
      { icon: "📊", title: "פעולה", body: "תדעו מה צריך לתקן אחר כך." },
    ],
  },
  benefits: {
    eyebrow: "יתרונות מרכזיים",
    titleStart: "כל מה שאפשר לראות",
    titleAccent: "ב-Shelf8",
    inventory: {
      tag: "מלאי",
      titleStart: "לשמור על המדפים",
      titleAccent: "מלאים",
      body: "ראו מה עומד להיגמר והזמינו מחדש לפני שלקוחות שמים לב.",
      list: [
        "לתפוס מלאי נמוך מוקדם",
        "להימנע ממדפים ריקים",
        "לעקוב אחרי שווי המלאי",
        "לדעת מה נמכר מהר",
      ],
      screenLabel: "מלאי",
      topCards: [
        { label: "במלאי", value: "7.0K" },
        { label: "שווי מלאי", value: "€31.2K" },
        { label: "SKU פעילים", value: "1.5K" },
      ],
      panelTitle: "מוצרים שצריכים תשומת לב",
      rows: [
        { label: "ביצי חופש 12 יח'", status: "1.9d · קריטי", tone: "danger" },
        { label: "גבינת צ'דר 200g", status: "6.4d · אזהרה", tone: "warning" },
        { label: "חלב 1L", status: "17.5d · OK", tone: "success" },
        { label: "בננות אורגניות", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "מכירות",
      titleStart: "לדעת מה באמת",
      titleAccent: "נמכר",
      body: "ראו אילו מוצרים מביאים כסף ואילו רק תופסים מקום על המדף.",
      list: [
        "לראות את המוצרים המובילים",
        "לזהות מוצרים איטיים",
        "לעקוב אחרי הכנסות ומרווח",
      ],
      screenLabel: "מכירות",
      topCards: [
        { label: "סה\"כ הכנסות", value: "€25.6K" },
        { label: "רווח גולמי", value: "€14.4K", tone: "success" },
        { label: "מרווח גולמי", value: "56.3%" },
      ],
      panelTitle: "המוצרים הנמכרים ביותר",
      rows: [
        { label: "אבוקדו", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "פולי אספרסו", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "פסטה", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "סלמון", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "התראות",
      titleStart: "לטפל בבעיות לפני",
      titleAccent: "שהן עולות לכם כסף",
      body: "ראו איפה אתם מפסידים כסף ומה כדאי לעשות עם זה.",
      list: [],
      screenLabel: "התראות",
      notices: [
        { icon: "📉", title: "הכנסה אבודה", body: "מוצרים חסרים במלאי — ואתם מפסידים הכנסה.", tone: "danger-soft" },
        { icon: "⚠️", title: "סיכון לפחת", body: "חלק מהמוצרים לא יימכרו לפני תאריך התפוגה.", tone: "warning-soft" },
        { icon: "💡", title: "הזדמנות מחיר", body: "שינויי מחיר קטנים יכולים להגדיל את ההכנסה.", tone: "success-soft" },
      ],
    },
  },
  examples: {
    eyebrow: "דוגמאות",
    titleStart: "לראות מה צריך",
    titleAccent: "פעולה היום",
    lead: "",
    cards: [
      {
        title: "החלב ייגמר בעוד יומיים",
        body: "להזמין מחדש לפני שהמדף מתרוקן.",
        icon: "🥛",
        badge: "LOW",
      },
      {
        title: "היוגורט לא נמכר מספיק",
        body: "להזמין פחות או לקדם אותו יותר.",
        icon: "🥣",
        badge: "SLOW",
      },
      {
        title: "הביצים נמכרות מהר, הגבינה נגמרת",
        body: "לסגור את הפער במלאי.",
        icon: "🥚",
        badge: "GAP",
      },
      {
        title: "הפחת במאפים גדל השבוע",
        body: "לפעול לפני שיאבד עוד מלאי.",
        icon: "🥐",
        badge: "WASTE",
      },
    ],
  },
  trust: {
    eyebrow: "הקמה",
    titleStart: "להשתמש בנתונים",
    titleAccent: "שכבר יש לכם",
    lead: "בלי הקמה מסובכת. שלחו את הקבצים שלכם וקבלו תמונה ברורה של החנות.",
    sourcesTitle: "מה אפשר לשלוח",
    sources: [
      {
        icon: "🧾",
        title: "קבלות",
        body: "קבלות קופה או ייצוא קבלות",
      },
      {
        icon: "📊",
        title: "ייצוא POS",
        body: "דוחות מכירה מהמערכת שכבר קיימת אצלכם",
      },
      {
        icon: "🗂️",
        title: "קבצי CSV",
        body: "גיליונות פשוטים שכבר קיימים אצל הצוות",
      },
      {
        icon: "📦",
        title: "קבצי מלאי",
        body: "ספירות מלאי ודוחות פריטים",
      },
    ],
    resultsTitle: "מה מקבלים",
    results: [
      "אנחנו מנקים ומסדרים את הנתונים שלכם.",
      "אנחנו מראים מה צריך תשומת לב.",
      "אתם מקבלים תצוגה יומית פשוטה.",
    ],
    note: "לא נדרשת הכשרה",
  },
  pricing: {
    eyebrow: "מחירים",
    titleStart: "לנסות בחינם.",
    titleAccent: "לראות תוצאות",
    lead: "להפחית פחת ולהימנע ממדפים ריקים עוד לפני שמתחילים לשלם.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "לחנות אחת שצריכה תמונה ברורה יותר של מכירות ומלאי.",
        list: [
          "דשבורדים למכירות ולמלאי",
          "תחזיות לחוסר מלאי לכל המוצרים",
          "עד 500 מוצרים",
          "רענון נתונים יומי",
          "התראות אימייל",
          "ללא צפייה מרובת סניפים",
          "ללא תחזית ביקוש",
        ],
        cta: "להתחיל חינם",
      },
      {
        tier: "Growth",
        badge: "הכי פופולרי",
        price: "€149",
        description: "לעסקים עם יותר מוצרים, יותר עובדים או יותר מסניף אחד.",
        list: [
          "כל מה שב-Starter",
          "עד 3 חנויות בתצוגה אחת",
          "עד 2,000 מוצרים",
          "ציוני פחת ותוקף",
          "תחזית ביקוש ל-14 יום",
          "אותות רגישות למחיר",
          "ללא white-label או API",
        ],
        cta: "קביעת דמו",
        featured: true,
      },
      {
        tier: "Partner",
        price: "מותאם",
        description: "לעסקים גדולים יותר ולשותפים שצריכים התאמה אישית.",
        list: [
          "ללא הגבלה על חנויות ומוצרים",
          "אפשרות ל-white-label",
          "גישה ל-API",
          "בנצ'מרק אנונימי",
          "תהליך onboarding ייעודי",
          "תמיכה מועדפת",
        ],
        cta: "יצירת קשר",
      },
    ],
  },
  cta: {
    eyebrow: "לקבוע דמו",
    titleStart: "לראות מה קורה",
    titleAccent: "בחנות שלכם",
    body: "קבעו דמו קצר וגלו איפה אתם מפסידים כסף.",
  },
  legal: {
    privacy: {
      title: "מדיניות פרטיות",
      lead: "מדיניות פרטיות זו מסבירה כיצד Shelf8 אוספת ומשתמשת במידע כאשר אתם גולשים באתר או קובעים שיחת דמו.",
      sections: [
        { title: "איזה מידע אנו אוספים", body: "אנו עשויים לאסוף פרטי קשר שתשלחו, מידע על הזמנה, מטא-דאטה של הדפדפן וניתוח שימוש בסיסי באתר." },
        { title: "כיצד אנו משתמשים במידע", body: "אנו משתמשים במידע כדי להגיב לפניות, לתאם הדגמות, לשפר את האתר ולתקשר על השירותים שלנו." },
        { title: "Calendly וצדדים שלישיים", body: "כאשר אתם מזמינים דמו, המידע עשוי להיות מעובד גם על ידי ספקי תזמון, וידאו, אנליטיקה ואחסון." },
        { title: "שמירת מידע", body: "אנו שומרים מידע רק למשך הזמן הסביר הדרוש להפעלת האתר, ניהול שיחות ועמידה בחובות משפטיות." },
        { title: "הזכויות שלכם", body: "ניתן לבקש גישה, תיקון או מחיקה של מידע אישי על ידי פנייה ל-hello@shelf8.com." },
        { title: "יצירת קשר", body: "שאלות בנושא פרטיות ניתן לשלוח ל-hello@shelf8.com." },
      ],
    },
    terms: {
      title: "תנאי שימוש",
      lead: "תנאי שימוש אלו חלים על הגישה לאתר Shelf8 ועל כל הזמנת דמו המתבצעת דרכו.",
      sections: [
        { title: "שימוש באתר", body: "מותר להשתמש באתר זה רק למטרות עסקיות חוקיות ואין לפגוע באבטחה או בזמינות שלו." },
        { title: "תוכן", body: "כל המיתוג, הטקסטים, הוויזואליה והחומרים באתר שייכים ל-Shelf8 אלא אם נאמר אחרת, ואין לעשות בהם שימוש חוזר ללא אישור." },
        { title: "הזמנות דמו", body: "זמינות הפגישות עשויה להשתנות. אנו רשאים להעביר או לדחות פגישה אם המועד שבחרתם אינו זמין עוד." },
        { title: "ללא הבטחה מסחרית", body: "המידע באתר ניתן למטרות מידע כלליות בלבד ואינו מבטיח תוצאה מסחרית כלשהי." },
        { title: "אחריות", body: "במידה המרבית המותרת לפי דין, Shelf8 אינה אחראית לנזקים עקיפים או תוצאתיים הנובעים מהשימוש באתר זה." },
        { title: "יצירת קשר", body: "שאלות לגבי תנאים אלו ניתן לשלוח ל-hello@shelf8.com." },
      ],
    },
  },
};

export const resources = {
  en: { translation: en },
  sr: { translation: sr },
  de: { translation: de },
  uk: { translation: uk },
  he: { translation: he },
};
