export const defaultLanguage = "en";
export const supportedLanguages = ["en", "sr", "de", "uk", "he"];
export const languageDirectionMap = {
  en: "ltr",
  sr: "ltr",
  de: "ltr",
  uk: "ltr",
  he: "rtl",
};

export const calendlyUrl = "https://calendly.com/prokopov94/30min";
export const contactEmail = "hello@shelf8.com";

export const languageOptions = [
  { code: "en", flag: "🇬🇧", label: "English" },
  { code: "sr", flag: "🇷🇸", label: "Srpski" },
  { code: "de", flag: "🇩🇪", label: "Deutsch" },
  { code: "uk", flag: "🇺🇦", label: "Українська" },
  { code: "he", flag: "🇮🇱", label: "עברית" },
];

const en = {
  meta: {
    landingTitle: "Shelf8 | Retail intelligence for grocery operators",
    landingDescription:
      "Shelf8 helps stores sell more, waste less, keep shelves full, and make daily decisions with less guesswork.",
    privacyTitle: "Privacy Policy | Shelf8",
    privacyDescription: "How Shelf8 collects, uses, and protects website and booking information.",
    termsTitle: "Terms of Use | Shelf8",
    termsDescription: "The terms that govern use of the Shelf8 website and booked demo calls.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Book a Demo",
    seeHowItWorks: "See How It Works",
    allRightsReserved: "All rights reserved.",
    menu: "Menu",
    close: "Close",
    freeBadge: "Free for the first 3 months",
    monthAfter: "/ month after",
    backHome: "Back to home",
    updated: "Last updated",
  },
  nav: {
    howItWorks: "How It Works",
    benefits: "Key Benefits",
    examples: "Examples",
    pricing: "Pricing",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
  },
  hero: {
    eyebrow: "For grocery stores and retail teams",
    titleStart: "Waste less food.",
    titleMiddle: "Keep shelves full.",
    titleAccent: "Grow sales.",
    subtitle:
      "See what sells well, what slows down, what needs reordering, and what may turn into waste.",
    metrics: [
      { label: "Revenue MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Gross Margin", value: "34.6%" },
      { label: "Inv. Turnover", value: "3.2×", note: "Healthy" },
    ],
    chartTitle: "Revenue by Category · 30 days",
    categories: [
      { label: "Beverages", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Dairy", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Seafood", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "Meat", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Stockout Predictions",
    stockouts: [
      { name: "Free-Range Eggs 12pk", meta: "Dairy · 40 units", status: "1.9d · Critical", tone: "danger" },
      { name: "Cheddar Cheese 200g", meta: "Dairy · 55 units", status: "6.4d · Warning", tone: "warning" },
      { name: "Whole Milk 1L", meta: "Dairy · 35 units", status: "17.5d · OK", tone: "success" },
      { name: "Sourdough Bread", meta: "Bakery · 143 units", status: "7.9d · OK", tone: "success" },
      { name: "Greek Yogurt 500g", meta: "Dairy · 93 units", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "How It Works",
    titleStart: "Upload your data.",
    titleAccent: "See what needs fixing",
    lead: "Send your reports or files. We show what to reorder, what to watch, and where you lose money.",
    steps: [
      {
        icon: "🔗",
        title: "Upload",
        body: "Upload receipts or reports.",
      },
      {
        icon: "⚙️",
        title: "Organize",
        body: "We organize everything.",
      },
      {
        icon: "🧠",
        title: "See Problems",
        body: "See problems in your stock.",
      },
      {
        icon: "📊",
        title: "Take Action",
        body: "Know what to fix next.",
      },
    ],
  },
  benefits: {
    eyebrow: "Key Benefits",
    titleStart: "What you can see",
    titleAccent: "inside Shelf8",
    inventory: {
      tag: "Inventory",
      titleStart: "Keep your shelves",
      titleAccent: "full",
      body: "See what is running out and reorder before customers notice.",
      list: [
        "Catch low stock early",
        "Avoid empty shelves",
        "Track stock value",
        "Know what sells fast",
      ],
      screenLabel: "Inventory",
      topCards: [
        { label: "Stock on Hand", value: "7.0K" },
        { label: "Inv. Value", value: "€31.2K" },
        { label: "Active SKUs", value: "1.5K" },
      ],
      panelTitle: "Products That Need Attention",
      rows: [
        { label: "Free-Range Eggs 12pk", status: "1.9d · Critical", tone: "danger" },
        { label: "Cheddar Cheese 200g", status: "6.4d · Warning", tone: "warning" },
        { label: "Whole Milk 1L", status: "17.5d · OK", tone: "success" },
        { label: "Organic Bananas", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Sales",
      titleStart: "Know what actually",
      titleAccent: "sells",
      body: "See which products bring money and which just take up space.",
      list: [
        "See top products",
        "Spot slow movers",
        "Track revenue and margin",
      ],
      screenLabel: "Sales",
      topCards: [
        { label: "Total Revenue", value: "€25.6K" },
        { label: "Gross Profit", value: "€14.4K", tone: "success" },
        { label: "Gross Margin", value: "56.3%" },
      ],
      panelTitle: "Best Sellers",
      rows: [
        { label: "Avocado", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Espresso Beans", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Pasta", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Salmon", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Alerts",
      titleStart: "Fix problems before",
      titleAccent: "they cost you",
      body: "See where you lose money and what to do about it.",
      list: [],
      screenLabel: "Alerts",
      notices: [
        {
          icon: "📉",
          title: "Lost Sales",
          body: "Products are out of stock — you are missing revenue.",
          tone: "danger-soft",
        },
        {
          icon: "⚠️",
          title: "Expiry Risk",
          body: "Some items will not sell before they expire.",
          tone: "warning-soft",
        },
        {
          icon: "💡",
          title: "Pricing Tip",
          body: "Small price changes can increase revenue.",
          tone: "success-soft",
        },
      ],
    },
  },
  examples: {
    eyebrow: "Examples",
    titleStart: "See what needs",
    titleAccent: "action today",
    lead: "",
    cards: [
      {
        title: "Milk may run out in 2 days",
        body: "Reorder before the shelf goes empty.",
        icon: "🥛",
        badge: "LOW",
      },
      {
        title: "Yogurt is not selling",
        body: "Order less or promote it.",
        icon: "🥣",
        badge: "SLOW",
      },
      {
        title: "Eggs sell fast, cheese runs out",
        body: "Fix the stock gap.",
        icon: "🥚",
        badge: "GAP",
      },
      {
        title: "Bakery waste is growing this week",
        body: "Act before more is lost.",
        icon: "🥐",
        badge: "WASTE",
      },
    ],
  },
  trust: {
    eyebrow: "Setup",
    titleStart: "Use the data",
    titleAccent: "you already have",
    lead: "No setup. Send your files and get a clear view of your store.",
    sourcesTitle: "What you can send",
    sources: [
      {
        icon: "🧾",
        title: "Receipts",
        body: "Till receipts or receipt exports",
      },
      {
        icon: "📊",
        title: "POS exports",
        body: "Sales reports from your current system",
      },
      {
        icon: "🗂️",
        title: "CSV files",
        body: "Simple spreadsheets your team already has",
      },
      {
        icon: "📦",
        title: "Inventory files",
        body: "Stock counts and product reports",
      },
    ],
    resultsTitle: "What you get",
    results: [
      "We clean and organize your data.",
      "We show what needs attention.",
      "You get a simple daily view.",
    ],
    note: "No training needed",
  },
  pricing: {
    eyebrow: "Pricing",
    titleStart: "Try it free.",
    titleAccent: "See the results",
    lead: "Reduce waste and avoid empty shelves before you pay.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "For one store that wants a clearer view of sales and stock.",
        list: [
          "Executive, sales, and inventory dashboards",
          "Stockout predictions for all products",
          "Up to 500 products",
          "Daily data refresh",
          "Email alerts",
          "No multi-store view",
          "No demand forecasting",
        ],
        cta: "Get Started Free",
      },
      {
        tier: "Growth",
        badge: "Most Popular",
        price: "€149",
        description: "For stores with more products, more staff, or more than one location.",
        list: [
          "Everything in Starter",
          "Up to 3 stores in one view",
          "Up to 2,000 products",
          "Waste and expiry risk scoring",
          "14-day demand forecast",
          "Price sensitivity signals",
          "No white-label or API",
        ],
        cta: "Book a Demo",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Custom",
        description: "For larger businesses and partners who need a custom setup.",
        list: [
          "Unlimited stores and products",
          "White-label option",
          "API access",
          "Anonymous benchmarking",
          "Dedicated onboarding",
          "Priority support",
        ],
        cta: "Talk to Us",
      },
    ],
  },
  cta: {
    eyebrow: "Book a Demo",
    titleStart: "See what is happening",
    titleAccent: "in your store",
    body: "Book a short demo and find where you are losing money.",
  },
  legal: {
    privacy: {
      title: "Privacy Policy",
      lead: "This Privacy Policy explains how Shelf8 collects and uses information when you browse the site or book a demo call.",
      sections: [
        { title: "Information We Collect", body: "We may collect contact details you submit, booking information, browser metadata, and high-level usage analytics needed to run the site." },
        { title: "How We Use Information", body: "We use submitted data to respond to inquiries, schedule demos, improve the site, and communicate about our services." },
        { title: "Calendly and Third Parties", body: "When you book a demo, your information may also be processed by third-party scheduling, video, analytics, and hosting providers." },
        { title: "Data Retention", body: "We keep information only for as long as reasonably necessary to operate the site, manage conversations, and meet legal obligations." },
        { title: "Your Rights", body: "You can request access, correction, or deletion of personal information by contacting us at hello@shelf8.com." },
        { title: "Contact", body: "Questions about privacy can be sent to hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Terms of Use",
      lead: "These Terms of Use govern access to the Shelf8 website and any demo booking made through it.",
      sections: [
        { title: "Website Use", body: "You may use this site for lawful business purposes only and may not interfere with its security or availability." },
        { title: "Content", body: "All branding, copy, visuals, and materials on this site belong to Shelf8 unless stated otherwise and may not be reused without permission." },
        { title: "Demo Bookings", body: "Demo availability is subject to change. We may reschedule or decline a meeting if the requested slot becomes unavailable." },
        { title: "No Commercial Guarantee", body: "Information on this site is provided for general informational purposes and does not guarantee any commercial outcome." },
        { title: "Liability", body: "To the fullest extent permitted by law, Shelf8 is not liable for indirect or consequential losses arising from use of this website." },
        { title: "Contact", body: "Questions about these terms can be sent to hello@shelf8.com." },
      ],
    },
  },
};

const sr = {
  meta: {
    landingTitle: "Shelf8 | Retail analitika za maloprodaju",
    landingDescription:
      "Shelf8 pretvara prodaju i zalihe u jasne dnevne odluke za prehrambene i maloprodajne timove.",
    privacyTitle: "Politika privatnosti | Shelf8",
    privacyDescription: "Kako Shelf8 prikuplja, koristi i štiti podatke sa sajta i rezervacija poziva.",
    termsTitle: "Uslovi korišćenja | Shelf8",
    termsDescription: "Uslovi koji uređuju korišćenje Shelf8 sajta i rezervaciju demo poziva.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Zakaži demo",
    seeHowItWorks: "Pogledaj kako radi",
    allRightsReserved: "Sva prava zadržana.",
    menu: "Meni",
    close: "Zatvori",
    freeBadge: "Prva 3 meseca besplatno",
    monthAfter: "/ mesečno nakon toga",
    backHome: "Nazad na početnu",
    updated: "Poslednje ažuriranje",
  },
  nav: {
    howItWorks: "Kako radi",
    benefits: "Ključne prednosti",
    pricing: "Cene",
    privacy: "Politika privatnosti",
    terms: "Uslovi korišćenja",
  },
  hero: {
    eyebrow: "Platforma za retail analitiku",
    titleStart: "Prva analitička platforma",
    titleAccent: "napravljena za vlasnike prodavnica i marketa",
    subtitle:
      "Povežite prodaju i zalihe sa komandnim centrom koji odmah pokazuje šta se prodaje, gde curi marža i šta zahteva reakciju.",
    metrics: [
      { label: "Prihod MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Bruto marža", value: "34.6%" },
      { label: "Obrt zaliha", value: "3.2×", note: "Stabilno" },
    ],
    chartTitle: "Prihod po kategoriji · 30 dana",
    categories: [
      { label: "Pića", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Mlečni proizvodi", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Riba", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "Meso", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Prognoza nestanka zaliha",
    stockouts: [
      { name: "Jaja 12 kom", meta: "Mlečni proizvodi · 40 kom", status: "1.9d · Kritično", tone: "danger" },
      { name: "Cheddar sir 200g", meta: "Mlečni proizvodi · 55 kom", status: "6.4d · Upozorenje", tone: "warning" },
      { name: "Mleko 1L", meta: "Mlečni proizvodi · 35 kom", status: "17.5d · OK", tone: "success" },
      { name: "Hleb od kiselog testa", meta: "Pekara · 143 kom", status: "7.9d · OK", tone: "success" },
      { name: "Grčki jogurt 500g", meta: "Mlečni proizvodi · 93 kom", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "Kako radi",
    titleStart: "Podaci ulaze.",
    titleAccent: "Uvidi izlaze.",
    lead: "Povežite postojeći POS i sistem zaliha. Shelf8 obrađuje podatke tokom noći i ujutru isporučuje jasne odluke.",
    steps: [
      { icon: "🔗", title: "Poveži", body: "Povežite POS, zalihe ili CSV izvoz kroz jedan kratak proces." },
      { icon: "⚙️", title: "Obradi", body: "Prodaja, stanje i marža se automatski čiste i strukturiraju." },
      { icon: "🧠", title: "Predvidi", body: "Svakog dana se računaju tražnja, rizik od nestanka i pritisak na prihod." },
      { icon: "📊", title: "Odluči", body: "Sveže kontrolne table i upozorenja čekaju vas pre otvaranja." },
    ],
    cards: [
      { number: "01", title: "Podešavanje za 30 minuta", body: "Bez razvoja. Povežite sistem i krenite brzo." },
      { number: "02", title: "Noćno osvežavanje", body: "Jutarni dashboard uvek otvara aktuelne brojeve." },
      { number: "03", title: "Metrike koje znače", body: "Prihod, marža, otpad i rizik od praznih rafova na jednom mestu." },
      { number: "04", title: "Upozorenja na vreme", body: "Reagujte pre nego što raf ostane prazan." },
    ],
  },
  benefits: {
    eyebrow: "Ključne prednosti",
    titleStart: "Sve kritične signale",
    titleAccent: "na jednom mestu",
    inventory: {
      tag: "Analitika zaliha",
      titleStart: "Znajte pre nego što",
      titleAccent: "ostanete bez zaliha",
      body: "Shelf8 pokazuje kada će proizvod verovatno pasti na nulu kako biste poručivali na osnovu trenutka, a ne osećaja.",
      list: [
        "Vreme do nestanka po proizvodu",
        "Kritično, upozorenje i stabilno",
        "Vrednost i obrt zaliha u jednom prikazu",
        "Brzina prodaje naspram trenutnog stanja",
      ],
      screenLabel: "Stanje zaliha",
      topCards: [
        { label: "Na stanju", value: "7.0K" },
        { label: "Vrednost zaliha", value: "€31.2K" },
        { label: "Aktivni SKU", value: "1.5K" },
      ],
      panelTitle: "Prognoza nestanka zaliha",
      rows: [
        { label: "Jaja 12 kom", status: "1.9d · Kritično", tone: "danger" },
        { label: "Cheddar sir 200g", status: "6.4d · Upozorenje", tone: "warning" },
        { label: "Mleko 1L", status: "17.5d · OK", tone: "success" },
        { label: "Organske banane", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Prodajni učinak",
      titleStart: "Pronađite šta pokreće",
      titleAccent: "vaš prihod",
      body: "Vidite koje kategorije donose profit, koji proizvodi ruše maržu i gde prihod tiho curi.",
      list: [
        "Top proizvodi po prihodu i bruto profitu",
        "Spori artikli pre nego što postanu otpad",
        "Marža po proizvodu i kategoriji",
        "30-dnevni trend prihoda sa čistim signalima",
      ],
      screenLabel: "Prodajni učinak",
      topCards: [
        { label: "Ukupan prihod", value: "€25.6K" },
        { label: "Bruto profit", value: "€14.4K", tone: "success" },
        { label: "Bruto marža", value: "56.3%" },
      ],
      panelTitle: "Top proizvodi po prihodu",
      rows: [
        { label: "Avokado", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Espresso kafa", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Fusilli 500g", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Filet lososa 300g", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Prediktivni uvidi",
      titleStart: "Prestanite da gubite prihod",
      titleAccent: "zbog praznih rafova",
      body: "Prognoza, rizik od otpada i cenovni signali pomažu da zaštitite maržu pre nego što nedelja izmakne kontroli.",
      list: [
        "Procena izgubljenog prihoda za svaki stockout",
        "14-dnevna prognoza tražnje po proizvodu",
        "Skorovi rizika od otpada i isteka",
        "Cenovni signali iz istorijskih obrazaca",
      ],
      screenLabel: "Uvidi i prognoze",
      notices: [
        { icon: "📉", title: "Izgubljen prihod · 30 dana", body: "Procena pokazuje €1,250 izgubljenog prihoda na tri proizvoda, uz najveći pad kod jaja i sira.", tone: "danger-soft" },
        { icon: "⚠️", title: "Rizik od otpada · 4 proizvoda", body: "Maslac, filet lososa i još dva artikla imaju povećan rizik od isteka prema trenutnoj brzini prodaje.", tone: "warning-soft" },
        { icon: "💡", title: "Cenovni signal · Paradajz sos", body: "Promena cene od 5% mogla bi da podigne prihod oko 8% na osnovu nedavnog ponašanja kupaca.", tone: "success-soft" },
      ],
    },
  },
  pricing: {
    eyebrow: "Cene",
    titleStart: "Transparentne cene.",
    titleAccent: "Bez iznenađenja.",
    lead: "Rani partneri dobijaju prva tri meseca besplatno, a zatim prelaze na fiksnu mesečnu cenu u evrima.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "Za jednu radnju kojoj treba bolja kontrola zaliha i marže.",
        list: [
          "Executive, prodajni i inventarski dashboardi",
          "Predikcija nestanka zaliha za sve proizvode",
          "Do 500 proizvoda",
          "Dnevno osvežavanje podataka",
          "Email upozorenja",
          "Bez prikaza više lokacija",
          "Bez prognoze tražnje",
        ],
        cta: "Počni besplatno",
      },
      {
        tier: "Growth",
        badge: "Najpopularniji",
        price: "€149",
        description: "Za rastuće operatore sa više lokacija, više SKU i složenijom operativom.",
        list: [
          "Sve iz Starter paketa",
          "Do 3 radnje u jednom prikazu",
          "Do 2.000 proizvoda",
          "Skorovi otpada i isteka",
          "14-dnevna prognoza tražnje",
          "Signali osetljivosti cene",
          "Bez white-label i API opcije",
        ],
        cta: "Zakaži demo",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Prilagođeno",
        description: "Za lance, distributere i platforme kojima treba prilagođen analitički sloj.",
        list: [
          "Neograničen broj radnji i proizvoda",
          "White-label opcija",
          "API pristup",
          "Anonimni benchmarking",
          "Posvećen onboarding",
          "Prioritetna podrška",
        ],
        cta: "Kontaktiraj nas",
      },
    ],
  },
  cta: {
    eyebrow: "Program ranih partnera",
    titleStart: "Spremni da vodite prodavnicu",
    titleAccent: "sa potpunom vidljivošću?",
    body: "Zakažite 30-minutni demo i pogledajte šta Shelf8 može da otkrije kroz prihod, zalihe, maržu i tražnju.",
  },
  legal: {
    privacy: {
      title: "Politika privatnosti",
      lead: "Ova Politika privatnosti objašnjava kako Shelf8 prikuplja i koristi podatke kada pregledate sajt ili zakažete demo poziv.",
      sections: [
        { title: "Koje podatke prikupljamo", body: "Možemo prikupljati kontakt podatke koje pošaljete, informacije o rezervaciji, metapodatke pregledača i osnovnu analitiku korišćenja sajta." },
        { title: "Kako koristimo podatke", body: "Podatke koristimo da odgovorimo na upite, zakažemo demo, unapredimo sajt i komuniciramo o našim uslugama." },
        { title: "Calendly i treće strane", body: "Kada zakažete demo, vaše informacije mogu obrađivati i provajderi za zakazivanje, video pozive, analitiku i hosting." },
        { title: "Čuvanje podataka", body: "Podatke čuvamo samo onoliko dugo koliko je razumno potrebno za rad sajta, vođenje komunikacije i ispunjavanje zakonskih obaveza." },
        { title: "Vaša prava", body: "Možete tražiti pristup, ispravku ili brisanje ličnih podataka kontaktiranjem na hello@shelf8.com." },
        { title: "Kontakt", body: "Pitanja o privatnosti možete poslati na hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Uslovi korišćenja",
      lead: "Ovi Uslovi korišćenja uređuju pristup Shelf8 sajtu i svaku demo rezervaciju napravljenu preko njega.",
      sections: [
        { title: "Korišćenje sajta", body: "Sajt možete koristiti samo u zakonite poslovne svrhe i ne smete ometati njegovu bezbednost ili dostupnost." },
        { title: "Sadržaj", body: "Brending, tekstovi, vizuali i materijali na ovom sajtu pripadaju Shelf8 osim ako nije drugačije navedeno i ne smeju se koristiti bez dozvole." },
        { title: "Demo rezervacije", body: "Dostupnost termina može se menjati. Možemo pomeriti ili odbiti sastanak ako izabrani termin više nije dostupan." },
        { title: "Bez poslovne garancije", body: "Informacije na sajtu služe opštem informisanju i ne garantuju bilo kakav komercijalni rezultat." },
        { title: "Odgovornost", body: "U meri dopuštenoj zakonom, Shelf8 ne odgovara za posredne ili posledične gubitke nastale korišćenjem ovog sajta." },
        { title: "Kontakt", body: "Pitanja o ovim uslovima pošaljite na hello@shelf8.com." },
      ],
    },
  },
};

const de = {
  meta: {
    landingTitle: "Shelf8 | Retail Intelligence fuer Lebensmittelhaendler",
    landingDescription:
      "Shelf8 verwandelt Verkaufs- und Bestandsdaten in klare taegliche Entscheidungen fuer Lebensmittel- und Retail-Teams.",
    privacyTitle: "Datenschutzerklaerung | Shelf8",
    privacyDescription: "Wie Shelf8 Website- und Buchungsdaten erhebt, nutzt und schuetzt.",
    termsTitle: "Nutzungsbedingungen | Shelf8",
    termsDescription: "Die Bedingungen fuer die Nutzung der Shelf8 Website und gebuchte Demo-Termine.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Demo buchen",
    seeHowItWorks: "So funktioniert es",
    allRightsReserved: "Alle Rechte vorbehalten.",
    menu: "Menue",
    close: "Schliessen",
    freeBadge: "Die ersten 3 Monate kostenlos",
    monthAfter: "/ Monat danach",
    backHome: "Zur Startseite",
    updated: "Zuletzt aktualisiert",
  },
  nav: {
    howItWorks: "So funktioniert es",
    benefits: "Vorteile",
    pricing: "Preise",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
  },
  hero: {
    eyebrow: "Retail-Intelligence-Plattform",
    titleStart: "Die erste Intelligence-Plattform",
    titleAccent: "fuer Inhaber von Lebensmittel- und Retail-Betrieben",
    subtitle:
      "Verbinden Sie Verkaufs- und Bestandsdaten mit einem Live-Control-Center, das zeigt, was verkauft wird, wo Marge verloren geht und was als Naechstes handeln verlangt.",
    metrics: [
      { label: "Umsatz MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Bruttomarge", value: "34.6%" },
      { label: "Lagerumschlag", value: "3.2×", note: "Stabil" },
    ],
    chartTitle: "Umsatz nach Kategorie · 30 Tage",
    categories: [
      { label: "Getraenke", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Molkerei", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Fisch", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "Fleisch", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Out-of-Stock-Prognosen",
    stockouts: [
      { name: "Freilandeier 12er", meta: "Molkerei · 40 Stk", status: "1.9d · Kritisch", tone: "danger" },
      { name: "Cheddar 200g", meta: "Molkerei · 55 Stk", status: "6.4d · Warnung", tone: "warning" },
      { name: "Vollmilch 1L", meta: "Molkerei · 35 Stk", status: "17.5d · OK", tone: "success" },
      { name: "Sauerteigbrot", meta: "Backwaren · 143 Stk", status: "7.9d · OK", tone: "success" },
      { name: "Griechischer Joghurt 500g", meta: "Molkerei · 93 Stk", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "So funktioniert es",
    titleStart: "Ihre Daten kommen rein.",
    titleAccent: "Klare Entscheidungen kommen raus.",
    lead: "Verbinden Sie Ihr bestehendes POS- und Bestandssystem. Shelf8 verarbeitet die Daten ueber Nacht und liefert morgens klare Handlungssignale.",
    steps: [
      { icon: "🔗", title: "Verbinden", body: "POS, Lager oder CSV-Exporte in einem kurzen Setup anbinden." },
      { icon: "⚙️", title: "Verarbeiten", body: "Verkauf, Bestand und Marge werden automatisch bereinigt und strukturiert." },
      { icon: "🧠", title: "Prognostizieren", body: "Nachfrage, Out-of-Stock-Risiko und Umsatzdruck werden jede Nacht berechnet." },
      { icon: "📊", title: "Entscheiden", body: "Aktuelle Dashboards und Alerts sind vor Ladenoeffnung bereit." },
    ],
    cards: [
      { number: "01", title: "Setup in 30 Minuten", body: "Keine Entwicklung noetig. Schnell anbinden und starten." },
      { number: "02", title: "Naechtliche Aktualisierung", body: "Am Morgen sehen Sie immer aktuelle Kennzahlen." },
      { number: "03", title: "Relevante Kennzahlen", body: "Umsatz, Marge, Verderb und Regalrisiko in einer Ansicht." },
      { number: "04", title: "Alerts rechtzeitig", body: "Handeln, bevor Regale leer werden oder Ware verdirbt." },
    ],
  },
  benefits: {
    eyebrow: "Vorteile",
    titleStart: "Alle kritischen Signale",
    titleAccent: "an einem Ort",
    inventory: {
      tag: "Bestandsintelligenz",
      titleStart: "Wissen, bevor",
      titleAccent: "etwas ausgeht",
      body: "Shelf8 zeigt, wann Produkte voraussichtlich auf null fallen, damit Nachbestellung auf Timing statt Vermutung basiert.",
      list: [
        "Zeit bis zum Stockout pro Produkt",
        "Kritisch-, Warn- und Healthy-Stufen",
        "Bestandswert und Umschlag in einer Sicht",
        "Verkaufstempo gegen aktuellen Bestand",
      ],
      screenLabel: "Bestandslage",
      topCards: [
        { label: "Bestand", value: "7.0K" },
        { label: "Bestandswert", value: "€31.2K" },
        { label: "Aktive SKU", value: "1.5K" },
      ],
      panelTitle: "Out-of-Stock-Prognosen",
      rows: [
        { label: "Freilandeier 12er", status: "1.9d · Kritisch", tone: "danger" },
        { label: "Cheddar 200g", status: "6.4d · Warnung", tone: "warning" },
        { label: "Vollmilch 1L", status: "17.5d · OK", tone: "success" },
        { label: "Bio-Bananen", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Verkaufsleistung",
      titleStart: "Erkennen Sie, was",
      titleAccent: "Ihren Umsatz treibt",
      body: "Sehen Sie, welche Kategorien Profit bringen, welche Produkte Marge kosten und wo Umsatz still verloren geht.",
      list: [
        "Top-Produkte nach Umsatz und Gewinn",
        "Langsamdreher vor Verderb erkennen",
        "Marge nach Produkt und Kategorie",
        "30-Tage-Umsatztrend mit klaren Signalen",
      ],
      screenLabel: "Verkaufsleistung",
      topCards: [
        { label: "Gesamtumsatz", value: "€25.6K" },
        { label: "Bruttogewinn", value: "€14.4K", tone: "success" },
        { label: "Bruttomarge", value: "56.3%" },
      ],
      panelTitle: "Top-Produkte nach Umsatz",
      rows: [
        { label: "Avocado", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Espressobohnen", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Fusilli 500g", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Lachsfilet 300g", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Praediktive Signale",
      titleStart: "Verlieren Sie keinen Umsatz mehr",
      titleAccent: "durch leere Regale",
      body: "Prognosen, Verderbrisiken und Preissignale helfen, Marge zu schuetzen, bevor die Woche entgleist.",
      list: [
        "Verlorener Umsatz je Stockout",
        "14-Tage-Nachfrageprognose pro Produkt",
        "Scores fuer Verderb und Ablaufdruck",
        "Preissignale aus historischen Mustern",
      ],
      screenLabel: "Insights & Prognosen",
      notices: [
        { icon: "📉", title: "Verlorener Umsatz · 30 Tage", body: "Der geschaetzte Umsatzverlust liegt bei €1,250 ueber drei Produkte, vor allem bei Eiern und Kaese.", tone: "danger-soft" },
        { icon: "⚠️", title: "Verderbrisiko · 4 Produkte", body: "Butter, Lachsfilet und zwei weitere Artikel zeigen auf Basis der aktuellen Geschwindigkeit ein erhoehtes Risiko.", tone: "warning-soft" },
        { icon: "💡", title: "Preissignal · Tomatensauce", body: "Eine Preisbewegung von 5% koennte den Umsatz gemaess juengstem Verhalten um etwa 8% steigern.", tone: "success-soft" },
      ],
    },
  },
  pricing: {
    eyebrow: "Preise",
    titleStart: "Transparente Preise.",
    titleAccent: "Keine Ueberraschungen.",
    lead: "Fruehe Partner erhalten die ersten drei Monate kostenlos und wechseln danach auf einen festen Euro-Monatspreis.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "Fuer einen Standort mit Bedarf an engerer Bestands- und Margenkontrolle.",
        list: [
          "Executive-, Sales- und Inventory-Dashboards",
          "Stockout-Prognosen fuer alle Produkte",
          "Bis zu 500 Produkte",
          "Taegliche Datenaktualisierung",
          "E-Mail-Alerts",
          "Kein Multi-Store-Blick",
          "Keine Nachfrageprognose",
        ],
        cta: "Kostenlos starten",
      },
      {
        tier: "Growth",
        badge: "Meistgewaehlt",
        price: "€149",
        description: "Fuer wachsende Betreiber mit mehr Filialen, mehr SKU und mehr operativer Komplexitaet.",
        list: [
          "Alles aus Starter",
          "Bis zu 3 Standorte in einer Sicht",
          "Bis zu 2.000 Produkte",
          "Scores fuer Verderb und Ablauf",
          "14-Tage-Nachfrageprognose",
          "Preissensitivitaetssignale",
          "Kein White-Label oder API",
        ],
        cta: "Demo buchen",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Individuell",
        description: "Fuer Ketten, Distributoren und Plattformen mit individuellem Analytics-Bedarf.",
        list: [
          "Unbegrenzte Standorte und Produkte",
          "White-Label-Option",
          "API-Zugang",
          "Anonymes Benchmarking",
          "Dediziertes Onboarding",
          "Priorisierter Support",
        ],
        cta: "Kontakt",
      },
    ],
  },
  cta: {
    eyebrow: "Early-Partner-Programm",
    titleStart: "Bereit, Ihren Betrieb",
    titleAccent: "mit voller Transparenz zu fuehren?",
    body: "Buchen Sie eine 30-minuetige Demo und sehen Sie genau, was Shelf8 bei Umsatz, Bestand, Marge und Nachfrage sichtbar macht.",
  },
  legal: {
    privacy: {
      title: "Datenschutzerklaerung",
      lead: "Diese Datenschutzerklaerung erklaert, wie Shelf8 Daten erhebt und nutzt, wenn Sie die Website besuchen oder eine Demo buchen.",
      sections: [
        { title: "Welche Daten wir erfassen", body: "Wir koennen Kontaktdaten, Buchungsinformationen, Browser-Metadaten und grundlegende Nutzungsanalysen erfassen." },
        { title: "Wie wir Daten nutzen", body: "Wir nutzen Daten, um auf Anfragen zu reagieren, Demos zu planen, die Website zu verbessern und ueber unsere Services zu kommunizieren." },
        { title: "Calendly und Drittanbieter", body: "Wenn Sie eine Demo buchen, koennen Ihre Daten auch von Termin-, Video-, Analyse- und Hosting-Anbietern verarbeitet werden." },
        { title: "Speicherdauer", body: "Wir speichern Daten nur so lange, wie es fuer Betrieb, Kommunikation und gesetzliche Pflichten angemessen erforderlich ist." },
        { title: "Ihre Rechte", body: "Sie koennen Zugang, Berichtigung oder Loeschung personenbezogener Daten ueber hello@shelf8.com anfordern." },
        { title: "Kontakt", body: "Fragen zum Datenschutz senden Sie bitte an hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Nutzungsbedingungen",
      lead: "Diese Nutzungsbedingungen regeln den Zugriff auf die Shelf8 Website und jede darueber gebuchte Demo.",
      sections: [
        { title: "Nutzung der Website", body: "Sie duerfen diese Website nur fuer rechtmaessige geschaeftliche Zwecke nutzen und ihre Sicherheit oder Verfuegbarkeit nicht beeintraechtigen." },
        { title: "Inhalte", body: "Marke, Texte, Visuals und Materialien auf dieser Website gehoeren Shelf8, sofern nicht anders angegeben, und duerfen nicht ohne Erlaubnis wiederverwendet werden." },
        { title: "Demo-Buchungen", body: "Verfuegbare Termine koennen sich aendern. Wir koennen Meetings verschieben oder ablehnen, wenn ein Slot nicht mehr verfuegbar ist." },
        { title: "Keine kommerzielle Garantie", body: "Die Informationen auf dieser Website dienen allgemeinen Informationszwecken und garantieren kein wirtschaftliches Ergebnis." },
        { title: "Haftung", body: "Soweit gesetzlich zulaessig, haftet Shelf8 nicht fuer indirekte oder Folgeschaeden aus der Nutzung dieser Website." },
        { title: "Kontakt", body: "Fragen zu diesen Bedingungen senden Sie bitte an hello@shelf8.com." },
      ],
    },
  },
};

const uk = {
  meta: {
    landingTitle: "Shelf8 | Retail-аналітика для продуктових операторів",
    landingDescription:
      "Shelf8 перетворює продажі та запаси на чіткі щоденні рішення для продуктових і retail-команд.",
    privacyTitle: "Політика конфіденційності | Shelf8",
    privacyDescription: "Як Shelf8 збирає, використовує та захищає дані сайту й бронювань.",
    termsTitle: "Умови використання | Shelf8",
    termsDescription: "Умови, що регулюють використання сайту Shelf8 і бронювання демо-дзвінків.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "Забронювати демо",
    seeHowItWorks: "Як це працює",
    allRightsReserved: "Усі права захищено.",
    menu: "Меню",
    close: "Закрити",
    freeBadge: "Перші 3 місяці безкоштовно",
    monthAfter: "/ місяць після цього",
    backHome: "Назад на головну",
    updated: "Оновлено",
  },
  nav: {
    howItWorks: "Як це працює",
    benefits: "Ключові переваги",
    pricing: "Ціни",
    privacy: "Політика конфіденційності",
    terms: "Умови використання",
  },
  hero: {
    eyebrow: "Платформа retail-аналітики",
    titleStart: "Перша аналітична платформа",
    titleAccent: "створена для власників магазинів і маркетів",
    subtitle:
      "Підключіть продажі та запаси до live-панелі, яка показує, що продається, де просідає маржа і що потребує дії просто зараз.",
    metrics: [
      { label: "Дохід MTD", value: "€34.6K", note: "+12.0%" },
      { label: "Валова маржа", value: "34.6%" },
      { label: "Оборот запасів", value: "3.2×", note: "Стабільно" },
    ],
    chartTitle: "Дохід за категоріями · 30 днів",
    categories: [
      { label: "Напої", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "Молочні продукти", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "Риба", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "М'ясо", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "Прогноз відсутності товару",
    stockouts: [
      { name: "Яйця 12 шт", meta: "Молочні продукти · 40 шт", status: "1.9d · Критично", tone: "danger" },
      { name: "Сир cheddar 200g", meta: "Молочні продукти · 55 шт", status: "6.4d · Увага", tone: "warning" },
      { name: "Молоко 1L", meta: "Молочні продукти · 35 шт", status: "17.5d · OK", tone: "success" },
      { name: "Хліб на заквасці", meta: "Пекарня · 143 шт", status: "7.9d · OK", tone: "success" },
      { name: "Грецький йогурт 500g", meta: "Молочні продукти · 93 шт", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "Як це працює",
    titleStart: "Дані заходять.",
    titleAccent: "Рішення виходять.",
    lead: "Підключіть поточний POS і систему запасів. Shelf8 обробляє дані вночі та зранку показує чіткі сигнали для дії.",
    steps: [
      { icon: "🔗", title: "Підключити", body: "Підключіть POS, склад або CSV-експорт у межах одного короткого setup." },
      { icon: "⚙️", title: "Обробити", body: "Продажі, залишки й маржа автоматично очищаються та структуруються." },
      { icon: "🧠", title: "Спрогнозувати", body: "Щоночі обчислюються попит, ризик stockout і тиск на дохід." },
      { icon: "📊", title: "Діяти", body: "Оновлені dashboards і alerts готові ще до відкриття магазину." },
    ],
    cards: [
      { number: "01", title: "Налаштування за 30 хвилин", body: "Без розробки. Підключили, перевірили, запустили." },
      { number: "02", title: "Нічне оновлення", body: "Зранку dashboard завжди відкривається на актуальних цифрах." },
      { number: "03", title: "Лише важливі метрики", body: "Дохід, маржа, ризик списань і порожніх полиць в одному місці." },
      { number: "04", title: "Сигнали вчасно", body: "Встигайте реагувати до того, як полиця спорожніє." },
    ],
  },
  benefits: {
    eyebrow: "Ключові переваги",
    titleStart: "Усі критичні сигнали",
    titleAccent: "в одному місці",
    inventory: {
      tag: "Аналітика запасів",
      titleStart: "Знайте до того, як",
      titleAccent: "товар закінчиться",
      body: "Shelf8 показує, коли позиція ймовірно впаде до нуля, щоб замовлення базувались на таймінгу, а не на здогадках.",
      list: [
        "Час до stockout по кожному товару",
        "Статуси критично, увага та стабільно",
        "Вартість і оборот запасів в одному вигляді",
        "Швидкість продажу проти поточного залишку",
      ],
      screenLabel: "Стан запасів",
      topCards: [
        { label: "У наявності", value: "7.0K" },
        { label: "Вартість запасів", value: "€31.2K" },
        { label: "Активні SKU", value: "1.5K" },
      ],
      panelTitle: "Прогноз відсутності товару",
      rows: [
        { label: "Яйця 12 шт", status: "1.9d · Критично", tone: "danger" },
        { label: "Сир cheddar 200g", status: "6.4d · Увага", tone: "warning" },
        { label: "Молоко 1L", status: "17.5d · OK", tone: "success" },
        { label: "Органічні банани", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "Продажі",
      titleStart: "Бачте, що саме",
      titleAccent: "рухає дохід",
      body: "Дивіться, які категорії приносять прибуток, які товари тиснуть на маржу і де дохід тихо втрачається.",
      list: [
        "Топ-товари за доходом і валовим прибутком",
        "Повільні позиції до того, як вони стануть списанням",
        "Маржа по товару й категорії",
        "30-денний тренд доходу без шуму",
      ],
      screenLabel: "Продажі",
      topCards: [
        { label: "Загальний дохід", value: "€25.6K" },
        { label: "Валовий прибуток", value: "€14.4K", tone: "success" },
        { label: "Валова маржа", value: "56.3%" },
      ],
      panelTitle: "Топ-товари за доходом",
      rows: [
        { label: "Авокадо", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "Кава еспресо", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "Fusilli 500g", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "Філе лосося 300g", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "Прогнозні інсайти",
      titleStart: "Не втрачайте дохід",
      titleAccent: "через порожні полиці",
      body: "Прогнози, ризик списань і цінові сигнали допомагають зберігати маржу до того, як тиждень вийде з-під контролю.",
      list: [
        "Оцінка втраченого доходу для кожного stockout",
        "14-денний прогноз попиту по товару",
        "Скоринг ризику списання та терміну придатності",
        "Цінові сигнали з історичних патернів",
      ],
      screenLabel: "Інсайти та прогнози",
      notices: [
        { icon: "📉", title: "Втрачений дохід · 30 днів", body: "Оцінка показує €1,250 втраченого доходу на трьох товарах, де основний внесок дали яйця та сир.", tone: "danger-soft" },
        { icon: "⚠️", title: "Ризик списання · 4 товари", body: "Масло, філе лосося та ще дві позиції мають підвищений ризик списання за поточною швидкістю продажу.", tone: "warning-soft" },
        { icon: "💡", title: "Ціновий сигнал · Томатний соус", body: "Зміна ціни на 5% може підняти дохід приблизно на 8% за останньою поведінкою покупців.", tone: "success-soft" },
      ],
    },
  },
  pricing: {
    eyebrow: "Ціни",
    titleStart: "Прозорі ціни.",
    titleAccent: "Без сюрпризів.",
    lead: "Ранні партнери отримують перші три місяці безкоштовно, а далі переходять на фіксовану ціну в євро.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "Для одного магазину, якому потрібен кращий контроль запасів і маржі.",
        list: [
          "Executive, sales і inventory dashboards",
          "Прогноз stockout для всіх товарів",
          "До 500 товарів",
          "Щоденне оновлення даних",
          "Email-сповіщення",
          "Без multi-store view",
          "Без прогнозу попиту",
        ],
        cta: "Почати безкоштовно",
      },
      {
        tier: "Growth",
        badge: "Найпопулярніший",
        price: "€149",
        description: "Для операторів, що зростають: більше локацій, більше SKU, більше операційної складності.",
        list: [
          "Усе зі Starter",
          "До 3 магазинів в одному view",
          "До 2 000 товарів",
          "Скоринг списання та закінчення терміну",
          "14-денний прогноз попиту",
          "Сигнали цінової чутливості",
          "Без white-label та API",
        ],
        cta: "Забронювати демо",
        featured: true,
      },
      {
        tier: "Partner",
        price: "Custom",
        description: "Для мереж, дистриб'юторів і платформ, яким потрібен кастомний аналітичний шар.",
        list: [
          "Необмежена кількість магазинів і товарів",
          "White-label опція",
          "Доступ до API",
          "Анонімний benchmarking",
          "Окремий onboarding",
          "Пріоритетна підтримка",
        ],
        cta: "Зв'язатися",
      },
    ],
  },
  cta: {
    eyebrow: "Програма ранніх партнерів",
    titleStart: "Готові керувати магазином",
    titleAccent: "з повною видимістю?",
    body: "Забронюйте 30-хвилинне демо і подивіться, що саме Shelf8 покаже по доходу, запасах, маржі та попиту.",
  },
  legal: {
    privacy: {
      title: "Політика конфіденційності",
      lead: "Ця Політика конфіденційності пояснює, як Shelf8 збирає та використовує дані, коли ви переглядаєте сайт або бронюєте демо.",
      sections: [
        { title: "Які дані ми збираємо", body: "Ми можемо збирати контактні дані, інформацію про бронювання, метадані браузера та базову аналітику використання сайту." },
        { title: "Як ми використовуємо дані", body: "Ми використовуємо дані, щоб відповідати на запити, планувати демо, покращувати сайт і комунікувати щодо наших послуг." },
        { title: "Calendly і треті сторони", body: "Коли ви бронюєте демо, ваші дані також можуть оброблятися сервісами бронювання, відеозв'язку, аналітики й хостингу." },
        { title: "Зберігання даних", body: "Ми зберігаємо дані лише стільки, скільки розумно необхідно для роботи сайту, комунікації та виконання юридичних обов'язків." },
        { title: "Ваші права", body: "Ви можете запросити доступ, виправлення або видалення персональних даних через hello@shelf8.com." },
        { title: "Контакт", body: "Питання щодо конфіденційності надсилайте на hello@shelf8.com." },
      ],
    },
    terms: {
      title: "Умови використання",
      lead: "Ці Умови використання регулюють доступ до сайту Shelf8 і кожне демо-бронювання, зроблене через нього.",
      sections: [
        { title: "Використання сайту", body: "Ви можете використовувати цей сайт лише для законних бізнес-цілей і не повинні порушувати його безпеку чи доступність." },
        { title: "Контент", body: "Брендинг, тексти, візуали та матеріали на цьому сайті належать Shelf8, якщо не зазначено інше, і не можуть використовуватись без дозволу." },
        { title: "Бронювання демо", body: "Доступність слотів може змінюватися. Ми можемо перенести або скасувати зустріч, якщо вибраний час більше недоступний." },
        { title: "Без комерційних гарантій", body: "Інформація на сайті надається для загального ознайомлення і не гарантує будь-якого комерційного результату." },
        { title: "Відповідальність", body: "У межах, дозволених законом, Shelf8 не несе відповідальності за непрямі або побічні збитки, пов'язані з використанням сайту." },
        { title: "Контакт", body: "Питання щодо цих умов надсилайте на hello@shelf8.com." },
      ],
    },
  },
};

const he = {
  meta: {
    landingTitle: "Shelf8 | מודיעין קמעונאי למפעילי מזון",
    landingDescription:
      "Shelf8 הופכת נתוני מכירות ומלאי להחלטות יומיות ברורות עבור צוותי קמעונאות ומזון.",
    privacyTitle: "מדיניות פרטיות | Shelf8",
    privacyDescription: "איך Shelf8 אוספת, משתמשת ומגנה על נתוני אתר והזמנות.",
    termsTitle: "תנאי שימוש | Shelf8",
    termsDescription: "התנאים החלים על השימוש באתר Shelf8 ועל הזמנת שיחות הדגמה.",
  },
  common: {
    brand: "Shelf8",
    email: contactEmail,
    bookDemo: "קביעת דמו",
    seeHowItWorks: "איך זה עובד",
    allRightsReserved: "כל הזכויות שמורות.",
    menu: "תפריט",
    close: "סגור",
    freeBadge: "3 החודשים הראשונים ללא תשלום",
    monthAfter: "/ לחודש לאחר מכן",
    backHome: "חזרה לדף הבית",
    updated: "עודכן לאחרונה",
  },
  nav: {
    howItWorks: "איך זה עובד",
    benefits: "יתרונות מרכזיים",
    pricing: "מחירים",
    privacy: "מדיניות פרטיות",
    terms: "תנאי שימוש",
  },
  hero: {
    eyebrow: "פלטפורמת מודיעין לקמעונאות",
    titleStart: "פלטפורמת המודיעין הראשונה",
    titleAccent: "שנבנתה לבעלי חנויות ורשתות מזון",
    subtitle:
      "חברו מכירות ומלאי למרכז שליטה חי שמראה מה נמכר, איפה המרווח נשחק ומה דורש פעולה עכשיו.",
    metrics: [
      { label: "הכנסות MTD", value: "€34.6K", note: "+12.0%" },
      { label: "רווח גולמי", value: "34.6%" },
      { label: "מחזור מלאי", value: "3.2×", note: "בריא" },
    ],
    chartTitle: "הכנסות לפי קטגוריה · 30 ימים",
    categories: [
      { label: "משקאות", value: "€6.2K", width: "92%", tone: "tone-900" },
      { label: "מוצרי חלב", value: "€4.8K", width: "71%", tone: "tone-700" },
      { label: "דגים", value: "€3.9K", width: "57%", tone: "tone-500" },
      { label: "בשר", value: "€2.3K", width: "33%", tone: "tone-300" },
    ],
    stockoutTitle: "תחזית חוסרי מלאי",
    stockouts: [
      { name: "ביצי חופש 12 יח'", meta: "מוצרי חלב · 40 יח'", status: "1.9d · קריטי", tone: "danger" },
      { name: "גבינת צ'דר 200g", meta: "מוצרי חלב · 55 יח'", status: "6.4d · אזהרה", tone: "warning" },
      { name: "חלב 1L", meta: "מוצרי חלב · 35 יח'", status: "17.5d · OK", tone: "success" },
      { name: "לחם מחמצת", meta: "מאפייה · 143 יח'", status: "7.9d · OK", tone: "success" },
      { name: "יוגורט יווני 500g", meta: "מוצרי חלב · 93 יח'", status: "27.9d · OK", tone: "success" },
    ],
  },
  pipeline: {
    eyebrow: "איך זה עובד",
    titleStart: "הנתונים נכנסים.",
    titleAccent: "ההחלטות יוצאות.",
    lead: "חברו את ה-POS ומערכת המלאי הקיימים. Shelf8 מעבדת את הנתונים בלילה ומספקת החלטות ברורות בבוקר.",
    steps: [
      { icon: "🔗", title: "חיבור", body: "חיבור POS, מלאי או קבצי CSV בתהליך קצר אחד." },
      { icon: "⚙️", title: "עיבוד", body: "מכירות, מלאי ומרווח מנוקים ומובנים אוטומטית." },
      { icon: "🧠", title: "חיזוי", body: "בכל לילה מחושבים ביקוש, סיכון לחוסר מלאי ולחץ על ההכנסה." },
      { icon: "📊", title: "פעולה", body: "דשבורדים והתראות מוכנים עוד לפני פתיחת החנות." },
    ],
    cards: [
      { number: "01", title: "הקמה ב-30 דקות", body: "ללא פיתוח. מחברים ומתחילים מהר." },
      { number: "02", title: "רענון לילי", body: "בבוקר הדשבורד תמיד נפתח על המספרים העדכניים." },
      { number: "03", title: "רק מה שחשוב", body: "הכנסות, מרווח, סיכון לפחת ולמדפים ריקים במקום אחד." },
      { number: "04", title: "התראות בזמן", body: "פועלים לפני שהמדף מתרוקן או שהמלאי הופך לפחת." },
    ],
  },
  benefits: {
    eyebrow: "יתרונות מרכזיים",
    titleStart: "כל האותות הקריטיים",
    titleAccent: "במקום אחד",
    inventory: {
      tag: "מודיעין מלאי",
      titleStart: "לדעת לפני",
      titleAccent: "שנגמר המלאי",
      body: "Shelf8 מראה מתי פריט צפוי לרדת לאפס כדי שהזמנה מחדש תתבסס על תזמון ולא על תחושת בטן.",
      list: [
        "זמן עד חוסר מלאי לכל מוצר",
        "מצבי קריטי, אזהרה ובריא",
        "שווי מלאי ומחזור במקום אחד",
        "קצב מכירה מול המלאי הנוכחי",
      ],
      screenLabel: "בריאות המלאי",
      topCards: [
        { label: "במלאי", value: "7.0K" },
        { label: "שווי מלאי", value: "€31.2K" },
        { label: "SKU פעילים", value: "1.5K" },
      ],
      panelTitle: "תחזית חוסרי מלאי",
      rows: [
        { label: "ביצי חופש 12 יח'", status: "1.9d · קריטי", tone: "danger" },
        { label: "גבינת צ'דר 200g", status: "6.4d · אזהרה", tone: "warning" },
        { label: "חלב 1L", status: "17.5d · OK", tone: "success" },
        { label: "בננות אורגניות", status: "9.1d · OK", tone: "success" },
      ],
    },
    sales: {
      tag: "ביצועי מכירה",
      titleStart: "לראות מה באמת",
      titleAccent: "מניע את ההכנסות",
      body: "גלו אילו קטגוריות יוצרות רווח, אילו מוצרים פוגעים במרווח ואיפה הכנסות דולפות בשקט.",
      list: [
        "המוצרים המובילים לפי הכנסה ורווח גולמי",
        "זיהוי איטיים לפני שהם הופכים לפחת",
        "מעקב מרווח לפי מוצר וקטגוריה",
        "מגמת הכנסות ל-30 יום ללא רעש",
      ],
      screenLabel: "ביצועי מכירה",
      topCards: [
        { label: "סה\"כ הכנסות", value: "€25.6K" },
        { label: "רווח גולמי", value: "€14.4K", tone: "success" },
        { label: "מרווח גולמי", value: "56.3%" },
      ],
      panelTitle: "מוצרים מובילים לפי הכנסה",
      rows: [
        { label: "אבוקדו", value: "€43.7K", width: "95%", tone: "tone-900" },
        { label: "פולי אספרסו", value: "€41.7K", width: "87%", tone: "tone-700" },
        { label: "פוזילי 500g", value: "€36.9K", width: "76%", tone: "tone-500" },
        { label: "פילה סלמון 300g", value: "€35.4K", width: "68%", tone: "tone-300" },
      ],
    },
    insights: {
      tag: "תובנות חיזוי",
      titleStart: "להפסיק לאבד הכנסות",
      titleAccent: "בגלל מדפים ריקים",
      body: "תחזיות, סיכון לפחת ואותות מחיר מקלים על שמירת המרווח לפני שהשבוע בורח.",
      list: [
        "אומדן הכנסה אבודה לכל stockout",
        "תחזית ביקוש ל-14 יום לכל מוצר",
        "ציוני סיכון לפחת ולפג תוקף",
        "אותות תמחור מדפוסים היסטוריים",
      ],
      screenLabel: "תובנות וחיזויים",
      notices: [
        { icon: "📉", title: "הכנסה אבודה · 30 ימים", body: "האומדן מצביע על €1,250 הכנסה אבודה בשלושה מוצרים, כשביצים וגבינה מובילים את הפער.", tone: "danger-soft" },
        { icon: "⚠️", title: "סיכון לפחת · 4 מוצרים", body: "חמאה, פילה סלמון ועוד שני פריטים מציגים סיכון גבוה יותר לפחת לפי הקצב הנוכחי.", tone: "warning-soft" },
        { icon: "💡", title: "אות מחיר · רוטב עגבניות", body: "שינוי מחיר של 5% עשוי להעלות הכנסה בכ-8% לפי התנהגות החנות לאחרונה.", tone: "success-soft" },
      ],
    },
  },
  pricing: {
    eyebrow: "מחירים",
    titleStart: "תמחור שקוף.",
    titleAccent: "בלי הפתעות.",
    lead: "שותפים מוקדמים מקבלים את שלושת החודשים הראשונים ללא תשלום ולאחר מכן עוברים למחיר חודשי קבוע ביורו.",
    plans: [
      {
        tier: "Starter",
        price: "€49",
        description: "לחנות אחת שצריכה שליטה טובה יותר במלאי ובמרווח.",
        list: [
          "דשבורדי executive, sales ו-inventory",
          "תחזיות stockout לכל המוצרים",
          "עד 500 מוצרים",
          "רענון נתונים יומי",
          "התראות אימייל",
          "ללא צפייה מרובת סניפים",
          "ללא תחזית ביקוש",
        ],
        cta: "להתחיל חינם",
      },
      {
        tier: "Growth",
        badge: "הכי פופולרי",
        price: "€149",
        description: "למפעילים בצמיחה עם יותר סניפים, יותר SKU ויותר מורכבות תפעולית.",
        list: [
          "כל מה שב-Starter",
          "עד 3 חנויות בתצוגה אחת",
          "עד 2,000 מוצרים",
          "ציוני פחת ותוקף",
          "תחזית ביקוש ל-14 יום",
          "אותות רגישות למחיר",
          "ללא white-label או API",
        ],
        cta: "קביעת דמו",
        featured: true,
      },
      {
        tier: "Partner",
        price: "מותאם",
        description: "לרשתות, מפיצים ופלטפורמות שצריכים שכבת אנליטיקה מותאמת.",
        list: [
          "ללא הגבלה על חנויות ומוצרים",
          "אפשרות white-label",
          "גישה ל-API",
          "Benchmarking אנונימי",
          "תהליך onboarding ייעודי",
          "תמיכה מועדפת",
        ],
        cta: "יצירת קשר",
      },
    ],
  },
  cta: {
    eyebrow: "תוכנית שותפים מוקדמים",
    titleStart: "מוכנים לנהל את החנות",
    titleAccent: "עם נראות מלאה?",
    body: "קבעו דמו של 30 דקות וראו בדיוק מה Shelf8 יכולה לחשוף על הכנסות, מלאי, מרווח וביקוש.",
  },
  legal: {
    privacy: {
      title: "מדיניות פרטיות",
      lead: "מדיניות פרטיות זו מסבירה כיצד Shelf8 אוספת ומשתמשת במידע כאשר אתם גולשים באתר או קובעים שיחת דמו.",
      sections: [
        { title: "איזה מידע אנו אוספים", body: "אנו עשויים לאסוף פרטי קשר שתשלחו, מידע על הזמנה, מטא-דאטה של הדפדפן וניתוח שימוש בסיסי באתר." },
        { title: "כיצד אנו משתמשים במידע", body: "אנו משתמשים במידע כדי להגיב לפניות, לתאם הדגמות, לשפר את האתר ולתקשר על השירותים שלנו." },
        { title: "Calendly וצדדים שלישיים", body: "כאשר אתם מזמינים דמו, המידע עשוי להיות מעובד גם על ידי ספקי תזמון, וידאו, אנליטיקה ואחסון." },
        { title: "שמירת מידע", body: "אנו שומרים מידע רק למשך הזמן הסביר הדרוש להפעלת האתר, ניהול שיחות ועמידה בחובות משפטיות." },
        { title: "הזכויות שלכם", body: "ניתן לבקש גישה, תיקון או מחיקה של מידע אישי על ידי פנייה ל-hello@shelf8.com." },
        { title: "יצירת קשר", body: "שאלות בנושא פרטיות ניתן לשלוח ל-hello@shelf8.com." },
      ],
    },
    terms: {
      title: "תנאי שימוש",
      lead: "תנאי שימוש אלו חלים על הגישה לאתר Shelf8 ועל כל הזמנת דמו המתבצעת דרכו.",
      sections: [
        { title: "שימוש באתר", body: "מותר להשתמש באתר זה רק למטרות עסקיות חוקיות ואין לפגוע באבטחה או בזמינות שלו." },
        { title: "תוכן", body: "כל המיתוג, הטקסטים, הוויזואליה והחומרים באתר שייכים ל-Shelf8 אלא אם נאמר אחרת, ואין לעשות בהם שימוש חוזר ללא אישור." },
        { title: "הזמנות דמו", body: "זמינות הפגישות עשויה להשתנות. אנו רשאים להעביר או לדחות פגישה אם המועד שבחרתם אינו זמין עוד." },
        { title: "ללא הבטחה מסחרית", body: "המידע באתר ניתן למטרות מידע כלליות בלבד ואינו מבטיח תוצאה מסחרית כלשהי." },
        { title: "אחריות", body: "במידה המרבית המותרת לפי דין, Shelf8 אינה אחראית לנזקים עקיפים או תוצאתיים הנובעים מהשימוש באתר זה." },
        { title: "יצירת קשר", body: "שאלות לגבי תנאים אלו ניתן לשלוח ל-hello@shelf8.com." },
      ],
    },
  },
};

export const resources = {
  en: { translation: en },
  sr: { translation: sr },
  de: { translation: de },
  uk: { translation: uk },
  he: { translation: he },
};
